### ISSUE TITLE
[Bug]: Empty selection on saved snapshot cannot be restored

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal#1000]
### What happened?

Snapshot with an empty selection on categorical variable will fail to load

### How to reproduce:

1. Run app below
2. Add filter variable "Species"
3. Unselect all species
4. Save snapshot
5. Download snapshot
6. Restore snapshot
    - Error occurs

### Sample code

```r
app <- init(
  data = teal_data(
    new_iris = iris,
    code = "new_iris <- iris"
  ),
  modules = modules(
    example_module()
  ),
  title = "App title"
)
if (interactive()) {
  shinyApp(app$ui, app$server)
}
#> Error in as.Date.default(slice[[field]]) : 
#>   do not know how to convert 'slice[[field]]' to class “Date”
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
Thanks, will have a look shortly
