### ISSUE TITLE
Warning when rendering tlg-catalog article with shiny app

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1023]
Tried with a randomly selected `/book/graphs/efficacy/fstg01.qmd` file and got the following:

```
[INFO] 2024-01-05 10:59:25.5618 pid:27497 token:[] teal.modules.clinical Initializing tm_g_forest_rsp
Warning in rlang::hash(hashables): 'package:teal.modules.clinical' may not be available when loading
```

**Comment by chlebowa** [comment]
Strange that the warning is raised by `hash`.
Could you provide a reproducible example?

**Comment by chlebowa** [comment]
Oh, I get a different one :shrug: 
```
$ quarto render book/graphs/efficacy/fstg01.qmd --no-cache


processing file: fstg01.qmd
  |..................................................  |  96% [snapshot]       
Quitting from lines 26-40 [snapshot] (fstg01.qmd)
Error:
! all repository entries must be named
Backtrace:
 1. withr::with_options(...)
 3. renv::snapshot(...)
 4. renv:::renv_repos_validate(repos)
 5. renv:::stopf("all repository entries must be named")
                                                                                                            
Execution halted
```

**Comment by pawelru** [comment]
Hmm strange... Let's focus on issues one by one and ignore this snapshotting - it's not relevant for this issue. Please comment out that line `{{< include ../../repro.qmd >}}` at the end of the file - this makes a new tab with session info and renv lock file.

**Comment by chlebowa** [comment]
Well...
![image](https://github.com/insightsengineering/teal/assets/114988527/d340a32b-ebad-4241-83ce-9315fae2999c)

**Comment by pawelru** [comment]
OK that was problem with my local packages. I reinstalled few and the problem is gone
