### ISSUE TITLE
Migrate from TealData to teal_data #988 Discussion - changj55 Comments

### ISSUE THREAD

**Issue by changjosh92** [insightsengineering/teal#1025]
These are comments made by changj55 about the recent migration info referenced in the title.

1. In "Changes summary" table, of the cell "Old" and "New" - can we reference the last versions of the teal package that this is more relevant for?

2. Immediately after the 'Changes summary' header, let's put a sentence to state that more details are found below the table.

3. In the section titled "Reproducible Code", I would probably get rid of the sentence "Previously, `teal_data()` and `dataset()` functions accepted code which were documenting origin of the data." 

and instead describe it as, 

"It was previously recommended to initialize your `teal_data()` by first specifying your data and then placing it in the `teal_data()` object. The new version of `teal_data()` is better used by initializing `teal_data()` as an empty object and then adding your data into it." 

or something to that effect. It is hard to understand what the phrase 'origin of the data' is meant to convey in the original wording.

Overall, just a little clean up with English grammar/sentence structure would be great to display a high caliber of thought put into the programming. Great progress so far all and thank you for putting in such effort with the documentation!

**Comment by changjosh92** [comment]
@gogonzo for visibility.

**Comment by gogonzo** [comment]
Addressed
