### ISSUE TITLE
init - data arg - Are we planning to keep supporting a "list of objects"? Note that they don't have to be either `data.frame` or `MAE` any more.

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1031]
Are we planning to keep supporting a "list of objects"? Note that they don't have to be either `data.frame` or `MAE` any more.

_Originally posted by @chlebowa in https://github.com/insightsengineering/teal/pull/1008#discussion_r1444811645_

**Comment by chlebowa** [comment]
Note that vignettes have been widely approved that state:

> All applications use the `teal_data` class as a data container. (_Including Data in teal Applications_)

**Comment by vedhav** [comment]
I don't see any real issue with us introducing this breaking change in this release.
`teal_data` can be used interchangeably with `list` which was not the case before when we had `TealData` classes. So, the need for list has vanished with this refactor and I don't see an older teal app that would work fine with the `TealData` -> `teal_data` refactor but relies on `list` to work, so it's broken anyway and this change is the easiest to adapt to.

**Comment by donyunardi** [comment]
I think I interpret the question the wrong way before I start reading the issue related to this. 🤦🏼 

Here's what I understand:
This is the current assertion in `init(data=)`:
https://github.com/insightsengineering/teal/blob/92301bc3ed46331c101cbf83990c2042ebb1cb9c/R/init.R#L122-L126

So this won't work:
![image](https://github.com/insightsengineering/teal/assets/8597300/72bc2fbd-ab18-41b3-ac56-cdd39a34893d)

But this will work (making it a named list)
![image](https://github.com/insightsengineering/teal/assets/8597300/273a22a5-2676-4294-93f5-f30ebcfcf284)

We prefer user to use teal_data() for the data argument so having this limitation (not allowing data to accept list of objects) feels okay to me. The hope is that user will be encouraged to learn about the object and at the very least, follow the right convention by passing a named list object to simplify the conversion to teal_data object.

I guess we can remove the skipped test.

**Comment by gogonzo** [comment]
Historically, `data = list(iris = iris)` was a nice alternative to 

```r
teal_data(
  dataset("iris", iris)
)
```

and this is why we still keep accepting `data` as a named list. I think `teal::init(data=)` should only accept `teal_data` or `teal_data_module`, so that:

```r
# accept this
init(data = teal_data(iris = iris), ...)

# instead of
init(data = list(iris = iris), ...)
```

`teal_data` call instead of `list` is still a one call vs one call.

**Comment by m7pr** [comment]
I would go with possibility to pass only `teal_data`/`teal_data_module` so we have less ways of input, hence less to explain (in documentation, vignettes and presentations), in already complex framework. If it's limited, then we can make user spend more time thinking on other aspects of the framework, instead of making him/her figure out what's more accesible for him/hem when passing the data and what's the difference (which is not really important).
