### ISSUE TITLE
fix documentation for `modules`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#1032]
Argument descriptions are wrong.

![image](https://github.com/insightsengineering/teal/assets/114988527/31edfea4-9466-4da1-bd43-1eef917831b6)

**Comment by chlebowa** [comment]
related: https://github.com/insightsengineering/teal/issues/942

**Comment by m7pr** [comment]
Closed with https://github.com/insightsengineering/teal/pull/1073 and https://github.com/insightsengineering/teal/pull/1053
