### ISSUE TITLE
Rename `getting-started-with-teal.Rmd` to `teal.Rmd` to have a dedicated "Getting started" button in pkgdown docs

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1039]
Currently it's missing on main
![image](https://github.com/insightsengineering/teal/assets/12943682/0725cc6b-f423-42bf-afd5-59232df82784)

Reference: https://pkgdown.r-lib.org/reference/build_articles.html#get-started

What bothers me is that it was like that in the last released version and someone changed this (for some reason - why?)
https://github.com/insightsengineering/teal/blob/v0.14.0/vignettes/teal.Rmd
![image](https://github.com/insightsengineering/teal/assets/12943682/ee5aedfe-f1c3-4fc6-ac66-d3aad0de75d5)

**Comment by pawelru** [comment]
@gogonzo 
Is there any particular reason why you renamed this in https://github.com/insightsengineering/teal/pull/992 ?

**Comment by chlebowa** [comment]
It was probably done to keep file names in line with vignette titles.
Also, there didn't use to be a `Blueprint`, that may have something to do with it.

**Comment by gogonzo** [comment]
> @gogonzo Is there any particular reason why you renamed this in #992 ?

@pawelru all the .md/.rmd files should follow the convention:
- lowercase
- kebab-case
- should be the same as title
 
 
I made a mistake by changing `teal.Rmd` - I didn't know the consequences in the pkgdown sections. I'll look first if this can be fixed in _pkgdown.yaml.

**Comment by pawelru** [comment]
Fine. This should be doable in the pkgdown file. You would have to manually link intro to that file name.
