### ISSUE TITLE
[Question]: example in README.md outdated?

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [insightsengineering/teal#1045]
### What is your question?

The [example in README.md](https://github.com/insightsengineering/teal/blob/7538ecb45fdc96c4de06a8deb0d48ae3d28afbd5/README.md?plain=1#L71-L100) does not work with the latest development version.

<pre>
Error:
! `dataset()` was deprecated in teal.data 0.3.1 and is now defunct.
ℹ Find more information on https://github.com/insightsengineering/teal/discussions/945
</pre>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
Sorry about that. It will be promptly corrected. In the mean time, please create your data with
`teal_data(iris = iris)` or `within(teal_data(), iris <- iris)`.

**Comment by donyunardi** [comment]
Fixed with 72f0d334a90665553cd298aa95450b21624bb3d3
Will be available after release.
Closing.
