### ISSUE TITLE
[Question]: `teal::module()` example outdated?

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [insightsengineering/teal#1046]
### What is your question?

https://github.com/insightsengineering/teal/blob/7538ecb45fdc96c4de06a8deb0d48ae3d28afbd5/R/modules.R#L208

`data[["iris"]]()` needs to be changed into `data()[["iris"]]` to make the example work with the current trunk version.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
Yes of course - an obvious mistake. Thanks for the ticket. Will be fixed in our clean-up

**Comment by donyunardi** [comment]
Fixed with d0d8739b9e7728b28bed314a7fb4b6eea2326610
Will be available after release.
Closing.
