### ISSUE TITLE
Strategy for testing examples with interactive app

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1047]
Most of our _app_ examples looks like this:
```
#' app <- init(...)
#' if (interactive()) {
#'   shinyApp(app$ui, app$server)
#' }
```

When checking the code, only `app` variable will be initiated and we do not (!) run the app which will cover server code. It's like defining the function vs executing it. As a result our examples might fail and this already happened (e.g. https://github.com/insightsengineering/teal/issues/1046). We need to came up with the strategy how to prevent it.

I have an idea to use `\dontshow{}` roxygen2 syntax to put some basic tests to cover server codes against some obvious mistakes. It won't be included in the final docs but it will be run during check (see the [docs](https://mpn.metworx.com/packages/roxygen2/7.1.0/articles/rd.html#functions:~:text=are%20summarised%20below.-,Command,-example)). In there, we might use `shinytest2` to and put some basic tests. If there will be a lot of overhead code - we can create an utility function. Just an idea - haven't really tried this (will do it tomorrow).

Please let me know your thoughts on this.

This might be relevant for modules packages as well.

**Comment by chlebowa** [comment]
I was wondering if it's possible to have an app start and kill itself after, say a second or two. That way an automated pipeline could actually run all all the apps but not capture the session indefinitely.

Anyway, I think the answer may lie in what @vedhav has been cooking up.

**Comment by pawelru** [comment]
When working on strict testing (incl. examples) I came up with mocking `shiny::runApp()`. Please take a look at this [draft PR](https://github.com/insightsengineering/teal.modules.clinical/pull/983). My aim is to trigger discussion and compare available solutions.

**Comment by pawelru** [comment]
I'm going to close it not to duplicate the space for discussion. Let's move it to the linked issue.

**Comment by averissimo** [comment]
How about creating a new issue to leverage `\dontshow` to hide the `if (interactive()) {` on examples? while allowing them to still pass R CMD check?

For example, the diff below passes `R CMD check` and shows like this

![image](https://github.com/insightsengineering/teal/assets/211358/7b8ec50b-81b4-46bb-a8f2-9227c0a41948)

```diff
diff --git a/R/init.R b/R/init.R
index 01af3c0ee..52391d08a 100644
--- a/R/init.R
+++ b/R/init.R
@@ -88,9 +88,9 @@
 #'   header = tags$h1("Sample App"),
 #'   footer = tags$p("Copyright 2017 - 2023")
 #' )
-#' if (interactive()) {
-#'   shinyApp(app$ui, app$server)
-#' }
+#' \dontshow{if (interactive()) \{ # is interactive }
+#' shinyApp(app$ui, app$server)
+#' \dontshow{ \} # is interactive }
 #'
 init <- function(data,
                  modules,
```

**Comment by chlebowa** [comment]
The parts in `\dontshow` are still run, so checking examples during R CMD CHECK will start an app that will keep running and the process will hang.
