### ISSUE TITLE
Merge the documentation page of `modules()` and `module()` in one page

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal#1074]
Initially raised in here https://github.com/insightsengineering/teal/pull/1073 by @chlebowa 
Similar issue is fixed here for unified documentation for `slices_store` and `slices_restore` https://github.com/insightsengineering/teal/pull/1072 by @averissimo 

Since examples are very similar for `modules()` and `module()` function, and since `modules()` have almost no `params` documented, maybe it's convenient to join documentation pages of those two into one manual page, especially since they are very similar and used together.

**Comment by donyunardi** [comment]
Let's merge them, thanks @m7pr !
