### ISSUE TITLE
reorder formals in `init`

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#1076]
```
init(
  data,
  modules,
  title = build_app_title(),
  filter = teal_slices(),
  header = tags$p(),
  footer = tags$p(),
  id = character(0)
)
```

I believe `filter` should come before `title`: `init(data, modules, filter, title, header, footer, id)`.

**Comment by pawelru** [comment]
I support this!
We have a good argument checking already so if one is relaying on the order then the error message should be meaningful enough to guide users what's wrong.

**Comment by chlebowa** [comment]
The unfortunate consequence of this change would be checking all example apps across all repositories.
Usually `init` calls pass named arguments but it is not guaranteed.

**Comment by kartikeyakirar** [comment]
I searched through insightengineering via https://github.com/search?q=org%3Ainsightsengineering+init%28&type=code&p=1 for all init() calls but did not find any examples that used positional arguments.

**Comment by chlebowa** [comment]
Well done @kartikeyakirar :+1: 
Green light then @donyunardi?

**Comment by donyunardi** [comment]
Alright, let's do it.
