### ISSUE TITLE
[Bug]:  padding added to app body when snapshot is added

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal#1078]
### What happened?

Whenever a snapshot is added to the application, padding-right is applied to the body element. To reproduce this issue, follow these steps:
1. Initialize the application.
2. Use the snapshot manager to add a snapshot.
3. Inspect the body element and observe its CSS properties.
4. Repeat step 2 once or twice.
5. Inspect the body element again and check its CSS properties.

Demonstration:

https://github.com/insightsengineering/teal/assets/6700955/bbfd5296-7043-43e3-be42-7bbc4ab701ab

**Comment by chlebowa** [comment]
Wow :open_mouth:

**Comment by chlebowa** [comment]
Upon closer inspection I notice that `padding-right` on `body` is increased by 15px when the cog icon is clicked and the modal opens. If the modal is closed, the padding is reverted. It is the act of saving a snapshot that makes the change premanent.

**Comment by chlebowa** [comment]
When a modal is opened, the `body` element gains an additional class, `modal-open`. It is that class that has the incrementing padding that is later transferred to `body` itself. This does not occur in a normal, non-`teal` app, the `modal-open` class has no added style.

**Comment by chlebowa** [comment]
Including our `teal` CSS in a non-`teal` app does not introduce the growing padding.
