### ISSUE TITLE
Reduce the size of sub-directories

### ISSUE THREAD

**Issue by vedhav** [insightsengineering/teal#1079]
As we have extensive docs for teal. The docs and help directory is populated with a lot of files.
We need to reduce the file size as we get a NOTE from R CMD check.

Possible solutions are to investigate unwanted files. Convert/Shrink them. Or remove and replace them with assets from a CDN.

**Comment by averissimo** [comment]
This size should be enough for the documentation: https://github.com/insightsengineering/hex-stickers/blob/main/thumbs/teal.png
