### ISSUE TITLE
[Question]: Can srv and ui funs of teal_module have additional arguments to those outlined in docs?

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1095]
### What is your question?

https://github.com/insightsengineering/teal/blob/0249281cf8b2de27af235915387420c89089994c/R/modules.R#L23-L34

If so, please document. Plus it's behaviour with regard to `ui_args` and `srv_args` - in particular: a literal match of list names vs formals names.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by averissimo** [comment]
> Can srv and ui funs of teal_module have additional arguments to those outlined in docs?

Can you elaborate on this? I may be misunderstanding the question as I believe this is documented on lines ~31 and ~34.

```R
#'  - `...` (optional) `server_args` elements will be passed to the module named argument or to the `...`. 

# and

#'  - `...` (optional) `ui_args` elements will be passed to the module named argument or to the `...`. 
```

> Plus it's behaviour with regard to ui_args and srv_args - in particular: a literal match of list names vs formals names.

There is a formals check when the `server` or `ui` function does not accept `...` as argument(s). That check is not being performed when the argument exists (even for the mandatory arguments... possible bug?) 

See below

``` r
mod <- teal::module(
  server = function(id, data, a, b = 2) {
    shiny::moduleServer(id, function(input, output, session) {
    # Server logic 
    })
  },
  ui = function(id, c) {
    # UI specifcation
  },
  ui_args = list(c = 1, z = "bla"),
  server_args = list(a = 2, b = 3, e = 1, f = 5)
)
#> Error in teal::module(server = function(id, data, a, b = 2) {: 
#> Following `server_args` elements have no equivalent in the formals of the server:
#>  - e
#>  - f
#> 
#> Update the server arguments by including above or add `...`
```

Possible bug as UI `c` argument is not on `ui_args`.

``` r
mod2 <- teal::module(
  server = function(id, data, a, b = 2, ...) {
    shiny::moduleServer(id, function(input, output, session) {
      # logic 
    })
  },
  ui = function(id, c, ...) {
    # UI specifcation
  },
  ui_args = list(z = "bla"),
  server_args = list(a = 2, b = 3, e = 1, f = 5)
)
```

```R
mod3 <- teal::module(
  server = function(id, data, a, b = 2, ...) {
    shiny::moduleServer(id, function(input, output, session) {
      # logic 
    })
  },
  ui = function(id, c, ...) {
    # UI specifcation
  },
  ui_args = list(c = 1, z = "bla"),
  server_args = list(a = 2, b = 3, e = 1, f = 5)
)
```

<sup>Created on 2024-06-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by pawelru** [comment]
Thanks @averissimo 

This make sense to me and I honestly cannot recall my concern. I'm going to close the issue and improve my future task description!
