### ISSUE TITLE
[Bug]: `TealAppDriver` setting numeric filter state

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal#1151]
`TealAppDriver$set_active_filter_selection` only works for categorical variables. It should also work for numeric ranges.

Example below of test that should work

```R
testthat::test_that("e2e: Set numeric filter state", {
  app <- TealAppDriver$new(
    data = simple_teal_data(),
    modules = example_module(label = "Example Module"),
    timeout = default_idle_timeout
  )
  withr::defer(app$stop())

  app$wait_for_idle()

  app$add_filter_var("iris", "Sepal.Length")
  app$view()
  app$set_active_filter_selection("iris", "Sepal.Length", c(4, 5), is_numeric = TRUE)
  app$wait_for_idle()
  testthat::expect_equal(
    app$get_active_filter_selection("iris", "Sepal.Length", is_numeric = TRUE), 
    c(4, 5)
  )
})
```

**Comment by chlebowa** [comment]
> ```r
>  app$set_active_filter_selection("iris", "Sepal.Length", c(4, 5), is_numeric = TRUE)
> ```

Are you sure you don't want to pass a `teal_slice`?

**Comment by averissimo** [comment]
That's a nice idea passing a `teal_slice`. It's familiar and avoids that `is_numeric` weirdness.

```r
app$set_active_filter_selection(
  teal_slice("iris", "Sepal.Length", selected = c(4, 5))
)
```

The operations that this call triggers would still be UI/input-based, but this would allow us to keep consistency.

Care to give insights on reasons to keep current formals @vedhav ?

**Comment by averissimo** [comment]
The `shinyWidgets::numericRangeInput` widget requires a custom handler to change the values.

I was able to do it via javascript, but if someone knows how to hint the handler via Shiny API, please chip in.

The caveat is that the input boxes still hold the previous values.

![image](https://github.com/insightsengineering/teal/assets/211358/79daddc4-f218-4f96-b7ce-c4dd7da66f5d)

![image](https://github.com/insightsengineering/teal/assets/211358/36248715-f1c9-447c-9969-335534d4f2fa)

**Comment by averissimo** [comment]
For that we need access to the `session` object, which I don't think we can easily access :-\

**Comment by averissimo** [comment]
I wasn't totally explicit in the description.

The issue here is that `AppDriver` API does nothing when setting for the input_id.
  - It seems that it sets them via javascript call
  - In turn, the javascript call via `Shiny.setInput` needs the handler suffix for some complex cases (such as the range input)

So the downstream javascript call needs to be `Shiny.setInput("an_input:sw.numericRange", [min, max])`

Which is what the PR does skipping all middle layers of `AppDriver`.
