### ISSUE TITLE
Remove `teal::show_rcode_modal` 

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal#1154]
There is an exported `show_rcode_modal` modal in `teal`. 

However if you seek for the usage of `show_rcode_modal` inside the whole organization, 
it only appears in `{teal.devel}` and [design/design_km.Rmd](https://github.com/insightsengineering/teal.modules.hermes/blob/bcea1efe2c2d90c8066b638bd86dd80c16a69512/design/design_km.Rmd#L125) in `{teal.modules.hermes}`. [Search results](https://github.com/search?q=org%3Ainsightsengineering%20show_rcode_modal&type=code)

I think this `modal` was replaced by `teal.widgets::verbatim_popup_ui(ns("rcode"), button_label = "Show R code")`. [Search results](https://github.com/search?q=org%3Ainsightsengineering+verbatim_popup&type=code)

**Comment by m7pr** [comment]
CC @gogonzo @pawelru @donyunardi

**Comment by pawelru** [comment]
great finding! Definitely to be removed!
This is type of things that I wanted to happen in https://github.com/insightsengineering/teal/issues/1007

**Comment by m7pr** [comment]
@pawelru @gogonzo @donyunardi just double checking. Should we remove this function immediately, or should we follow the deprecation cycle? We could release a version with this function being deprecated, and in 2 months (or whatever is our retention period) release a version of `teal` with this function being removed.

**Comment by gogonzo** [comment]
@m7pr we go through deprecation process whenever possible. I would deprecate in this case as well
