### ISSUE TITLE
[Feature] Adding `wait_for_idle` in the constructor of `TealAppDriver`

### ISSUE THREAD

**Issue by vedhav** [insightsengineering/teal#1163]
How about adding the `wait_for_idle` here instead of using it after `TealAppDriver$new` on each single test?

I also suggest re-implementing `wait_for_idle` to increase the timeout of the `TealAppDriver`, wdyt?

```suggestion
      private$set_active_ns()
      self$wait_for_idle()
    },
    wait_for_idle = function(duration = 500, timeout = 20000) {
      super$wait_for_idle(duration = duration, timeout = timeout)
    },
```

_Originally posted by @averissimo in https://github.com/insightsengineering/teal/pull/1127#discussion_r1521365360_

**Comment by m7pr** [comment]
This is great and I already need that!
I think the `app$click()` could also benefit from the extension of `$wait_for_idle()` as those are the two situations in which I always use `$wait_for_idle`

**Comment by m7pr** [comment]
Hey @averissimo and @vedhav - I created a PR in here for implement this, but left 2 questions for a serious discussion https://github.com/insightsengineering/teal/pull/1171
