### ISSUE TITLE
Is it possible to install teal v.0.14.0?

### ISSUE THREAD

**Issue by Mia-data** [insightsengineering/teal#1165]
### What is your question?

Hi,

I have my teal app written based on v.0.14.0. My colleague wants to use it and tried to install teal v0.14.0 but in CRAN Archive this version is not available. He also tried to install from github by devtools::install_github("insightengineering/teal@v0.14.0") but without sucess.

Could you please advice how to install older version (v0.14.0) of teal package?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
You can put a link to the github file directly in the `install.packages` function.

```r
install.packages("https://github.com/insightsengineering/teal/archive/refs/tags/v0.14.0.tar.gz", repos = NULL)
```

However, I tried to install `0.14.0` but without a success. 
Probably because other packages (like `teal.code` or `teal.data`) need to be downgraded as well.
We would need to check what versions of `teal.code`, `teal.slice` and `teal.data` were released the moment `teal` `0.14.0` was released and redo the direct version installation process for those imported packages as well.

```r
install.packages("https://github.com/insightsengineering/teal/archive/refs/tags/v0.14.0.tar.gz", repos = NULL)
trying URL 'https://github.com/insightsengineering/teal/archive/refs/tags/v0.14.0.tar.gz'
downloaded 1.8 MB

Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package 'teal' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning messages:
1: package 'shiny' was built under R version 4.3.2 
2: package 'teal.data' was built under R version 4.3.2 
Error in get(x, envir = ns, inherits = FALSE) : 
  object 'list_to_teal_slices' not found
Error: unable to load R code in package 'teal'
Execution halted
ERROR: lazy loading failed for package 'teal'
```

**Comment by m7pr** [comment]
`teal` `0.14.0` was release on `Aug 14, 2023` . The very same day we released
- https://github.com/insightsengineering/teal.slice/releases/tag/v0.4.0
- https://github.com/insightsengineering/teal.code/releases/tag/v0.4.0
- https://github.com/insightsengineering/teal.data/releases/tag/v0.3.0

So the installation process could be as follows

```r
install.packages("https://github.com/insightsengineering/teal.code/archive/refs/tags/v0.4.0.tar.gz", repos = NULL)
install.packages("https://github.com/insightsengineering/teal.data/archive/refs/tags/v0.3.0.tar.gz", repos = NULL)
install.packages("https://github.com/insightsengineering/teal.slice/archive/refs/tags/v0.4.0.tar.gz", repos = NULL)
install.packages("https://github.com/insightsengineering/teal/archive/refs/tags/v0.14.0.tar.gz", repos = NULL)
```

In this particular order, as for `Aug 14, 2023` `teal` imported `teal.slice` that imported `teal.data`

**Comment by Mia-data** [comment]
Thank you for your quick reply! I VERY APPRECIATE IT! :smile:
