### ISSUE TITLE
[Feature Request]: Remove "Show warnings" feature

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1176]
### Feature description

As we move away from `chunks` in favour of `qenv` I see little point of having this functionality. I propose to remove it complitely.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by m7pr** [comment]
@pawelru just to clarify, we are planning to remove `Show Warnings` verbatim popup from all modules, which e.g. for `tm_missing_data` would be the removal of:

- UI https://github.com/insightsengineering/teal.modules.general/blob/46dc21951b7b44a8d36513eb2a8eb94c3f56da6e/R/tm_missing_data.R#L231
- Server part https://github.com/insightsengineering/teal.modules.general/blob/46dc21951b7b44a8d36513eb2a8eb94c3f56da6e/R/tm_missing_data.R#L1272-L1277

And that happens for all modules that we have?

<img width="631" alt="image" src="https://github.com/insightsengineering/teal/assets/133694481/07d5ffa3-c2f9-4ca5-a45a-deee525bb840">

**Comment by pawelru** [comment]
Yes. That's correct.

**Comment by pawelru** [comment]
> So I guess we won't need `teal.code::get_warnings()` https://github.com/insightsengineering/teal.code/blob/main/R/qenv-get_warnings.R and handling warnings during `teal.code::eval_code()` https://github.com/insightsengineering/teal.code/blob/main/R/qenv-eval_code.R#L68-L71 ? If this is not used by any module

This I don't know. It's quite likely but you would have to check it.

**Comment by gogonzo** [comment]
> So I guess we won't need `teal.code::get_warnings()` https://github.com/insightsengineering/teal.code/blob/main/R/qenv-get_warnings.R and handling warnings during `teal.code::eval_code()` https://github.com/insightsengineering/teal.code/blob/main/R/qenv-eval_code.R#L68-L71 ? If this is not used by any module

I think it makes sense to keep `get_warnings` in `teal.data`. Somebody might need it in custom modules or in its custom framework.

**Comment by m7pr** [comment]
in `teal.data` or in `teal.code` :)? `get_warnings` was introduced in `teal.code`

**Comment by m7pr** [comment]
I created 4 PRs to remove this functionality from our modules.

@kartikeyakirar , since @gogonzo and @pawelru are away due to the banking holiday tomorrow, would you mind to review?
The goal was to remove `Show Warnings` from the UI (hence the server as well) of all modules that we have. Thanks!

https://github.com/insightsengineering/teal.modules.general/pull/749
https://github.com/insightsengineering/teal.modules.clinical/pull/1180
https://github.com/insightsengineering/teal.osprey/pull/264
https://github.com/insightsengineering/teal.goshawk/pull/273
