### ISSUE TITLE
[Question]: Use of `teal` module in other `shiny` apps.

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#1225]
### What is your question?

https://github.com/insightsengineering/teal/blob/06a0a581a132590e85cb147d9ab1853558ab150e/R/module_teal.R#L26

Is this still relevant if the module is not exported?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
Thanks @kartikeyakirar  Will `ui_teal_with_splash` remain exported indefinitely?

**Comment by kartikeyakirar** [comment]
Although using `teal `as a module is not recommended, if necessary, it can be done via the `teal_with_splash` module. Therefore, I do not see this becoming internal in the foreseeable future.

**Comment by m7pr** [comment]
Thanks @chlebowa for raising this. I created an issue for that https://github.com/insightsengineering/teal/issues/1244 so we dont forget
