### ISSUE TITLE
[Feature Request]: Make a new data-summary

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#1226]
Blocked by https://github.com/insightsengineering/teal/issues/1229

1. Module should produce the same table as `FilteredData$ui_overview`. 
    - arguments: `id`, `data` (reactive teal_data)
    - output: reactive teal_data
2. Module's server should be called just before passing data to the teal_module ([look here](https://github.com/insightsengineering/teal/blob/5c3e3fd4380ef0fc7efc53ec1cdf4f5a7c922dd3/R/module_nested_tabs.R#L213))
3. Beware that instead of `data` (`teal_data`), `datasets` (`FilteredData`) object could be still used in a module, and transform can't be performed on `FilteredData`. Please include summary under condition `is_arg_used(modules$server, "data")`
4. Module's ui should be included in a relevant place to inform how data have changed in a "transformation".

Hide existing filter-panel-summary so we don't need to make changes in teal.slice. Please keep in mind [this issue](https://github.com/insightsengineering/teal.slice/issues/4)

**Comment by kumamiao** [comment]
Prefers to have it within the module (and collapsable if possible) instead of a separate tab

**Comment by gogonzo** [comment]
> Prefers to have it within the module (and collapsable if possible) instead of a separate tab

What do you mean specifically? 
If you want this in the teal_module, then it will be in the encoding panel, and it will be something which module-developer will have to add (call the summary-module inside of own teal_module). 

Current idea is that summary will be inserted in the sidebar where filter-panel is and where teal_transform will be. Every item in this sidebar will be collapsible.

**Comment by m7pr** [comment]
@gogonzo just double checking we want this to be a feature implemented in `teal` based on a feature we had in `teal.slice`?
