### ISSUE TITLE
[Feature Request]: Implement a teal_transform_module

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#1228]
### Feature description

See this [file](https://github.com/insightsengineering/teal/blob/e06ffc3602603eddb902f4158f4793b2a0e635dd/R/teal_data_transform_module.R) where most of the work is done.

- `teal_transform_module`'s `ui` and `server` should be consumed in `ui/srv_nested_tabs` [just after creation of teal_data object](https://github.com/insightsengineering/teal/blob/5c3e3fd4380ef0fc7efc53ec1cdf4f5a7c922dd3/R/module_nested_tabs.R#L211). 
- Beware that instead of `data` (`teal_data`), `datasets` (`FilteredData`) object could be still used in a module, and transform can't be performed on `FilteredData`. Please include transform under condition `is_arg_used(modules$server, "data")`
- Add validates for `reactive teal_data` [find here](https://github.com/insightsengineering/teal/blob/e06ffc3602603eddb902f4158f4793b2a0e635dd/R/teal_data_module-validate.R)

**Comment by donyunardi** [comment]
Can we close this? @averissimo @gogonzo
