### ISSUE TITLE
teal_transform_module vignette

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#1231]
Vignette describing `teal_transform_module`, should contain:

- what is `teal_transform_module`
- how transform works in `teal`
- how to create a module which uses transformers
- showcase the app with some transformers

Please edit `data-transform-as-shiny-module.Rmd` file

**Comment by donyunardi** [comment]
I believe @vedhav did this already with #1283 
Can this be closed?

**Comment by vedhav** [comment]
I think we can add a sample app in `teal.gallery` with the transform feature. I will do this today and we can close this.

**Comment by gogonzo** [comment]
@donyunardi existing vignette needs to be redacted. Vignette is missing "how to create a module which uses transforms". Plus, I'd remove a section "Custom placement of the transform UI" for now, I think we need to discuss the placement of the transform again.

**Comment by gogonzo** [comment]
> I think we can add a sample app in teal.gallery with the transform feature. I will do this today and we can close this.

Good idea 👍

**Comment by donyunardi** [comment]
> I think we can add a sample app in teal.gallery with the transform feature. I will do this today and we can close this.

Shouldn't we make a new issue for this? Sounds like we're extending the scope of this issue which is only to create a vignette.

**Comment by vedhav** [comment]
Yes, We can close this one. The [custom-transform app](https://genentech.shinyapps.io/nest_custom-transform_dev/) is deployed and we can take the discussion about that app on the PR https://github.com/insightsengineering/teal.gallery/pull/177
