### ISSUE TITLE
do we need list wraped around module?

### ISSUE THREAD

**Issue by kartikeyakirar** [insightsengineering/teal#1235]
![image](https://github.com/insightsengineering/teal.connectors.ssh/assets/211358/5a23b153-3baa-497b-8fc7-c7cd1f5d86e1)

 based on [code](https://github.com/insightsengineering/teal/blob/main/R/init.R#L120-L130) if it's a single module, wrap it around a` list`. I feel it's older code and should be wrapped around `teal_modules` instead. But I am a bit unsure if its for added flexibility or should removing the older code .

 @donyunardi @gogonzo  Can you confirm this?

_Originally posted by @kartikeyakirar in https://github.com/insightsengineering/teal.connectors.ssh/pull/1#discussion_r1616079387_

**Comment by donyunardi** [comment]
That snippet of code was added with [this PR](https://github.com/insightsengineering/teal/pull/795).
The idea is to allow flexibility when passing the object to the `modules` argument.
With the update, users can wrap a single module with `list()` or `modules()`, or just pass the module object directly to the `modules` argument.

So the answer is no, users don't need `list()` wrapped around a single module. However, we allow a single module to be wrapped in `list()`.

**Comment by chlebowa** [comment]
I recall, there was some discussion around this later on, before CRAN release, and @pawelru insisted that `list` remain a valid input.

**Comment by kartikeyakirar** [comment]
thanks @donyunardi and @chlebowa
