### ISSUE TITLE
Make `progress` argument optional for all modified functions

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal#1243]
Initially stated in here https://github.com/insightsengineering/teal/pull/1236#issuecomment-2160469324

> [Can I ask to] make progress argument optional for all modified functions? The rationale here is simplicity - we would like to keep the requirements to run the funcs to the meaningful minimum which is in these case: id, modules and datasets. If you look at the functions definitions all the other arguments (incl. filter which is also quite important) has some defaults. In case of progress this could be NULL and if it's Progress we will increment it. Another benefits are in testing - no need to create a dummy progress object to execute functions.

> (*) I know the is.missing() stuff but IMHO having x = NULL in the function definition exposes this better without reading docs or function body

**Comment by pawelru** [comment]
done in https://github.com/insightsengineering/teal/pull/1241

**Comment by m7pr** [comment]
Lol, sorry
