### ISSUE TITLE
[Feature Request]: <Import the navbarMenu layout for the modules function>

### ISSUE THREAD

**Issue by kaipingyang** [insightsengineering/teal#1246]
### Feature description

The modules function provides a **tabsetPanel** layout to nest modules, which is great.
But when there are too many TFL modules, the page will appear crowded.
![image](https://github.com/insightsengineering/teal/assets/55199277/327f944e-5141-49ab-884a-6bfe4d965732)

Can we enhance the modules function by adding the **navbarMenu** layout?
![image](https://github.com/insightsengineering/teal/assets/55199277/05d7cdfc-e783-4f61-b346-8c01e826e1e1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
I completely agree with you @kaipingyang and we've been discussing this as well in https://github.com/insightsengineering/teal/issues/534

I'll close this as duplicate but feel free to contribute on that issue if you have other ideas or suggestion.
