### ISSUE TITLE
[Question]: Plotly usage in teal

### ISSUE THREAD

**Issue by zwu-cims** [insightsengineering/teal#1262]
### What is your question?

Does teal support plotly output. Could you give an example if possible? Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
Hi @zwu-cims thanks for reaching us out. Yes it is possible. Here is an example app using single plotly module 

```r
library(teal)
library(ggplot2)
library(plotly)


# teal module using plotly
app <- teal::init(
  data = teal.data::teal_data(faithful = faithful),
  modules = modules(
    module(
      ui = function(id) {
        ns <- NS(id)
        plotly::plotlyOutput(ns("plot"))
      },
      server = function(id, data) {
        moduleServer(id, function(input, output, session) {
          output$plot <- plotly::renderPlotly({
            g <- ggplot(data()[["faithful"]], aes(x = eruptions, y = waiting)) +
              stat_density_2d(aes(fill = after_stat(level)), geom = "polygon") +
              xlim(1, 6) +
              ylim(40, 100)
            ggplotly(g)
          })
        })
      }
    )
  )
)

shinyApp(app$ui, app$server)
```

<img width="1512" alt="image" src="https://github.com/insightsengineering/teal/assets/6959016/fb4ba204-c1a1-4a16-98a0-4360bc5e910e">

**Comment by shajoezhu** [comment]
dear @zwu-cims , could you do us a favor and ask this question on stackflow again? We would like to move our questions to StackOverflow, and once the question is there, we will create and tag it by `nest-teal`  this is going to help many more user in the future! Thank you!

**Comment by zwu-cims** [comment]
Sure of course. Does teal have a StackOverflow page where I can post my question on?
