### ISSUE TITLE
Possibility to disable lockfile creation

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1276]
In the projects like TLG-Catalog, where we produce a lot of small apps for WebR
I want to be able to disable lockfile creation

**Comment by m7pr** [comment]
@pawelru if this is urgent, as a quick fix for now you can provide a path to an empty file via `options('teal.renv.lockfile')`

**Comment by m7pr** [comment]
To disable lockfile creation this function should return `NULL` https://github.com/insightsengineering/teal/pull/1263/files#diff-c389a151f2967297002c1253ee7819f95d9017f250147356c6e8d6d66165638cR59-R73
We could set this up with an R option via `options`. `options('teal.renv.create = TRUE)'` by default, that can be set to `FALSE`?

**Comment by pawelru** [comment]
Yes. That's what I was thinking of. A new option would have to be documented properly of course.

**Comment by pawelru** [comment]
I am observing more and more unusual times when `teal_app.lock` file is being generated:
- rendering quarto article with teal app code
- running examples with `devtools::run_examples()`
- my experimental roxygen roclet running examples

That all makes me think that we should be more restrictive on when to trigger creating this file.

**Comment by m7pr** [comment]
@pawelru we can always switch to the case when this is run on demand by a parameter in init. `init(lockfile = FALSE)` 

```r
@param lockfile `(logical)` whether to generate the lockfile for the app. by default FALSE
```

This will be easier to turn it on, then detect places where it it problematic

**Comment by pawelru** [comment]
I honestly have to admit that I am not super convinced to do this. I do really like how simple `init()` is. For me, all the arguments needs to be of the same _importance_ level. Now let's compare that new argument against `data` or `modules` to see what I am concerned about.
I don't really know how to proceed. This might be indeed good to allow to control but don't want to disrupt current simplicity of init

**Comment by m7pr** [comment]
So we will end up controlling everything with `options()` because we don't like arguments : ) and that ain't gonna be simple, because you need extra documentation for `options` used in teal, and that is not very popular way of modifying functions' behaviors (in comparison to arguments usage). We can introduce one meta argument, that takes a list or arguments as an input, and that's gonna be the place for the placement of all custom low-important parameters?
Still thinking out loud. Not necessarily pushing any idea

**Comment by gogonzo** [comment]
Cases when we should include lockfile process:
- a running app (normal shiny app) on
- interactive session (for example by running testServer by hand) on
- r cmd check/tests off
- devtools::run examples off
- tlg-catalog
  - webshot-callr off
  - webr shinylive on

**Comment by m7pr** [comment]
> But this won't work because if the "parent" process has teal loaded and runs callr::, then the option is hand over and it won't be possible to change it within callr.

Had the very same intuition about it, but it looks like `callr` starts a new process and no parent options are used. Those are the print screens of how it works via `reprex::reprex` that starts a new session and run what was copied to the clipboard

<img width="829" alt="image" src="https://github.com/user-attachments/assets/80afbdd7-a893-4dd0-a7d6-e82d7a5911f4">

and the same for `teal` and the option

<img width="894" alt="image" src="https://github.com/user-attachments/assets/d0fc03c3-378c-4eee-a002-d6feffdf56d6">

**Comment by m7pr** [comment]
When it comes to `tlg-catalog`, their current build actually runs the lockfile creation so this is good moment that we will prevent that

https://github.com/insightsengineering/tlg-catalog/actions/runs/10864227371/job/30149260781

<img width="940" alt="image" src="https://github.com/user-attachments/assets/e69436eb-a733-47c2-9a9d-ac38a9a920eb">

**Comment by m7pr** [comment]
For the tlg-catalog, it's not `webshot` who calls `callr`, but it's Quarto that renders teal apps (and webshot then make print-screens of those apps). So this should be just refined to: disable teal lockfile creation on Quarto processes

<img width="138" alt="image" src="https://github.com/user-attachments/assets/bb6b5fb6-251b-4056-bb8e-66f9d910f83d">

**Comment by gogonzo** [comment]
Addressed here https://github.com/insightsengineering/teal/pull/1263
