### ISSUE TITLE
[Bug]: `warning('Code was not verified for reproducibility.')` shown twice in `Show R Code`

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal#1286]
Run simple app

```r
app <- init(
  data = teal_data(iris = iris, mtcars = mtcars),
  modules = example_module()
)
shinyApp(app$ui, app$server)
```

on `669_insertUI@main` branch, and click `Show R Code`. The warning about `teal_data()` not been verified is shown twice

<img width="668" alt="image" src="https://github.com/user-attachments/assets/721b68b3-ecbc-4d08-9dd8-77de2af6e44f">

**Comment by gogonzo** [comment]
Fixed
