### ISSUE TITLE
[Bug]: Error/warning message when data is not sufficient and no teal transform modules

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#1299]
### What happened?

When data provided to the `teal::init` has insufficient datasets and none of the modules have `teal_transform_module` specified it clearly means that some modules are missing some datasets.

What we need is to make an assert/warning in teal::init to throw message when:
- datasets available in `data` argument don't cover all possible `modules$datanames`
- None of the modules have `transforms` specified (means that list of datasets won't be extended by teal_transform_module)

When we address https://github.com/insightsengineering/teal/issues/1298 it will be possible to determine all possible datanames including those created in `teal_transform_module` so the message will be thrown when:
- datasets available in `data` argument don't cover all possible `modules$datanames` and `teal_transform_module$datanames`

**Comment by m7pr** [comment]
Proposition for an improvement in here https://github.com/insightsengineering/teal/pull/1309, but blocked by https://github.com/insightsengineering/teal/issues/1298

**Comment by m7pr** [comment]
Hey, I provided a PR for the top part of the issue https://github.com/insightsengineering/teal/pull/1319 and there is an open DRAFT for the second part of the issue https://github.com/insightsengineering/teal/pull/1320 but this is blocked by https://github.com/insightsengineering/teal/issues/1298

**Comment by m7pr** [comment]
Closed with https://github.com/insightsengineering/teal/pull/1319
