### ISSUE TITLE
User experience for failures of teal_transform_module

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#1304]
### Summary

Currently, users can apply multiple `teal_transform_module` instances to a module.

If one of the `teal_transform_module` fails, the current behavior is as follows:
* Validation or assertion occurs to warn users that the transformation cannot be completed. In addition, the border box around the `teal_transform_module` will turn red to visually inform the user that the transformation failed to run.
* The data continues to be passed to the other `teal_transform_module` for processing.

To illustrate this, let's say a teal module has two `teal_transform_module` instances assigned to it:
1. The first `teal_transform_module` creates or mutates a new variable in a dataset.
2. The second `teal_transform_module` renames several values in a column.

If the first `teal_transform_module` fails, the app user can still execute the second `teal_transform_module`. This is the current behavior of our `teal_transform_module` feature.

The concern is that if the `teal_transform_module` represents sequential steps in generating a certain analysis for a teal module, it may not make sense to allow the user to execute the second `teal_transform_module` until the issue with the first one is resolved. By doing this, app users may be prevented from generating incorrect analyses or plots.

Then, what is better UX for failures in teal_transform_module?
1. Keep current behavior (ignore error from failing teal_transform_module and pass (unmodified) data further).
2. Prevent other `teal_transform_module` to run, if the first one fail, by passing error further. It will require adding req(data()) in all observeEvent and renderXyz added in teal_transform_module.

**Comment by donyunardi** [comment]
@kumamiao 
Personally, I like the current behavior, which allows the data to continue moving forward for execution on other `teal_transform_module` instances, leaving the responsibility for the accuracy of the analysis with the app user or app developer.

However, I'd love to hear your opinion from an analyst's perspective.

**Comment by kumamiao** [comment]
Hi @donyunardi I personally would prefer the 2nd option as an analyst, which I think would also be the preference of the app user. For example, if `transform_module_1` is creating new variables, and `transform_module_2` is data transposing based on the new variables created from step 1, and then the analysis is based on the new columns after the transposing. Then to me it should fail at the transformation step, instead of at the analysis level, where the analysis will fail for sure.

>Then, what is better UX for failures in teal_transform_module?
> 
> 1. Keep current behavior (ignore error from failing teal_transform_module and pass (unmodified) data further).
> 2. Prevent other teal_transform_module to run, if the first one fail, by passing error further. It will require adding req(data()) in all observeEvent and renderXyz added in teal_transform_module.

**Comment by donyunardi** [comment]
> For example, if transform_module_1 is creating new variables, and transform_module_2 is data transposing based on the new variables created from step 1, and then the analysis is based on the new columns after the transposing. Then to me it should fail at the transformation step, instead of at the analysis level, where the analysis will fail for sure.

Let's assume we have `transform_module_3` which is not related with data steps of `transform_module_1` or `transform_module_2`. Should `transform_module_3` be executed or should it be halted because `transform_module_1` is failing?

**Comment by kumamiao** [comment]
Ideally there would be this data dependency issue, i.e., if `transform_module_3` is based on a separate data that was not used for `transform_module_1` or `transform_module_2`, then the `transform_module_3` step would still execute. Only that the user would still not get analysis results because `transform_module_1` step fails, assuming the end data in `transform_module_1` and `transform_module_1` is needed for the analysis.

**Comment by donyunardi** [comment]
> Only that the user would still not get analysis results because transform_module_1 step fails, assuming the end data in transform_module_1 and transform_module_1 is needed for the analysis.

I think you meant _assuming the end data in **transform_module_2** and **transform_module_3** is needed for the analysis._

If that's the case, does it still make sense to halt the execution of `transform_module_2`, given that the analysis will be incorrect anyway if another unrelated transformation fails?

Also, if `transform_module_1` fails and we halt the execution of `transform_module_2`, what happens to the visualization (plot or table)? Will the user still see something, or do we throw an error?

**Comment by kumamiao** [comment]
If `transform_module_2` depends on `transform_module_1` and transform_module_1 fails, then we should halt execution of `transform_module_2`.

> If that's the case, does it still make sense to halt the execution of transform_module_2, given that the analysis will be incorrect anyway even if another unrelated transformation made it through?

In terms of the visualization, if the visualization is dependent on the data generated from `transform_module_1` (together with `transform_module_2` and `transform_module_3`), I think there would not be a visualization output shown in the output panel, but throw and error. But if for some reason the visualization is solely dependent on `transform_module_3`, then I would think in that case the visualization would still show as it's not impacted by the error.

**Comment by donyunardi** [comment]
After discussing with @kumamiao, we concluded that:

1. The teal framework should not be responsible for or guarantee the accuracy of a teal module's analysis. This responsibility lies with the teal module developer.
2. A teal app developer can create an optional `teal_transform_module`, meaning the app user may choose whether or not to run the transformation.

> Then, what is better UX for failures in teal_transform_module?
> 1. Keep current behavior (ignore error from failing teal_transform_module and pass (unmodified) data further).
> 2. Prevent other `teal_transform_module` to run, if the first one fail, by passing error further. It will require adding req(data()) in all observeEvent and renderXyz added in teal_transform_module.

Given these considerations, we believe that the current behavior of `teal_transform_module` (option 1) is preferable. Any additional validation or assertions needed to ensure a correct analysis should be handled within the teal module function, managed by teal module developer.

Of course, we can still discuss this further, so feel free to share your thoughts.
cc @pawelru @insightsengineering/nest-core-dev

**Comment by pawelru** [comment]
I have been always thinking about 2. I have actually never thought about 1 or to be precise: I believe that the design of 1 is flawed.

What you described is a typical piping schema where the output from LHS of pipe operator is passed to the RHS of pipe operator. 

correct example:
```
❯ echo "test test" | xargs echo | xargs echo
test test
```

In case of error it stops eagerly. It does not return. We are not entering the following step.
```
❯ echo "test test" | xargs echo | error | xargs echo
zsh: command not found: error
```

In case of R:
correct example:
```
r$> 1 |> add_one() |> add_one()
[1] 3
```
eager stop on error:
```
r$> 1 |> add_one() |> this_is_error() |> add_one()
Error in this_is_error(add_one(1)) : 
  could not find function "this_is_error"
```

I do see teal.transform as a sort of interactive-dplyr. Let's see what non-interactive dplyr does:
correct example:
```
r$> iris |> mutate(x = 1) |> mutate(y = 2) |> head(1)
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species x y
1          5.1         3.5          1.4         0.2  setosa 1 2
```
stop on error:
```
r$> iris |> mutate(x = 1) |> mutate(z = stop()) |> mutate(y = 2) |> head(1)
Error in `mutate()`:
ℹ In argument: `z = stop()`.
Run `rlang::last_trace()` to see where the error occurred.
```

This is not only incorrect design but also could lead to incorrect results. This is super important!
Let's say I already have column X and in the transformation step I am doing `X = foo(X, ...)`. If `foo()` throws and we continue on error then I will be having column X and that can be then used further.
You might argue that this will be visible in the GUI but every GUI settings can be overwritten, elements might be collapsed etc. Errors in values calculation must be present in the values itself - not only GUI.

I would strongly suggest to revisit this strategy again.

**Comment by vedhav** [comment]
Interesting points @pawelru. I agree that our functions should be designed this way.
The main distinction between piping operations mentioned above and `teal_transformers` is that the custom `teal_transformers` are user-defined (app developers, who are generally not experienced R developers), There is more potential for failures. Currently, we handle these failures by showing error messages in the transform module and also directly inside the module, it is hard to ignore.
Additionally, incorrect user inputs can easily break the custom transform if not handled properly. So, it becomes a trade-off between making the module work or suppressing the module output when data flow has errors.

I would ~be okay~ prefer hiding the module output when there are errors.

**Comment by pawelru** [comment]
This is great that we are presenting the errors. My point was more about that teal-transform element should not return input value in case of error. This feels to me incorrect and might lead to further incorrect values.

A module might return something else other than a visualisation. Let's say I'm having an application with custom module with transformers. That module creates a visualisation as well as send me an email with the report. Let's say I programmed a bot that does clicks in the GUI. The bot will see errors in the GUI but incorrect results are being carried forward and the report was calculated on the wrong data and then sent to me. 

If we must return from transform step to make the whole app to continue working - let's return NULL or `rlang::zap()` instead. (and apply req assertions at the beginning of transform and module).

**Comment by donyunardi** [comment]
Thanks for the feedback @pawelru

I would argue that there is no guarantee that the correct analysis can be achieved even if all transformations are executed. It ultimately depends on how the teal module is written. If a result of transformation is crucial, the teal module should be designed to capture it. This is why, in my opinion, the accuracy of the analysis should be the responsibility of the teal module developer, not the teal framework. 

As @vedhav pointed out, with the GUI and error messages provided in the teal module and the teal transform card, I was also hoping this is enough to alert users while still getting the best experience when using teal.

![image](https://github.com/user-attachments/assets/c3af34af-26e8-4d3d-875c-aaf926f0043a)

If a user decides to overwrite the UI or hiding elements as you mentioned, then it's beyond our control, and they should be prepared to face the consequences of doing so.

I may have had my own opinion on how I think users should experience the transformer feature but to be clear, I have nothing against making the transformer feature stricter when used in a teal module. If that’s the scope we want to pursue, then let's do it. I really don’t mind going either way. It may not be a big deal to stop the module execution and hide the output if we can design it properly.

**Comment by kumamiao** [comment]
Thanks all for the great discussion. 

I like that we're highlighting the errors, but it's a valid point that the UI can also be hided (or ignored if the user does not directly interact with the GUI). I guess the options are:

1. Continue with the current approach and leave the responsibilities to the users to ensure the accuracy of the results
2. If **ANY** of the teal transform module fails, then the analysis will not get run and output panel may return NULL or an error message about the transform module error. - I'm not sure how long this would take for the team. @donyunardi maybe we could do an evaluation within the team on the feasibility to complete this by the end of this sprint?
3. Design a logic to fail transform modules - I personally think this could get a bit complicated (and one could argue that this may be beyond the scope of `teal` framework itself), as a proper design would involve identifying the potential dependencies across all of the transform modules and different scenarios, as well as analysis that dependent on certain modules, as discussed previously. This would very unlikely to get completed in this PI.

With the process of the current PI (a lot to do in the next couple of sprints), I would propose to either go with 1 or 2 (2 if feasible), and do a feature enhancement in future PIs. @pawelru let me know what you think, thanks!

**Comment by vedhav** [comment]
After a discussion with @gogonzo we concluded that it becomes hard for the users to interpret the data flow when we start to fallback on previous data (this information is not signaled anywhere, and a teal app user might not be aware that this happens under the hood).
This is what we will do to handle the errors:
1. We will display the error on the first transform failure with the error message that causes this error.
2. The subsequent transforms will not run because an error occurred in the upstream transformation and show a generic error message.
3.  When this happens, we will completely hide this module's output and display an error message instead of the output.

Here's the recording of this behavior:

https://github.com/user-attachments/assets/746abe89-5255-41ab-9a30-fec54baeff89
