### ISSUE TITLE
[Bug]: `._raw_` datasets should not be shown in the `Show R Code`

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal#1311]
`._raw_` datasets got into the `Show R Code` somehow - https://genentech.shinyapps.io/nest_basic-teal_dev/

````r
library(dplyr)
IRIS <- iris %>% mutate(Species1 = Species, Species2 = Species, Species3 = Species, Species4 = Species, Species5 = Species)
MTCARS <- mtcars
stopifnot(rlang::hash(IRIS) == "1caadedc699b329d8d427daee0696be1")
stopifnot(rlang::hash(MTCARS) == "d0487363db4e6cc64fdb740cb6617fc0")
IRIS._raw_ <- IRIS
MTCARS._raw_ <- MTCARS
IRIS <- dplyr::filter(IRIS, Sepal.Width > 2.5 & Petal.Length > 1.5)
MTCARS <- dplyr::filter(MTCARS, gear == 3)
````

![image](https://github.com/user-attachments/assets/92e46f6d-e39d-4309-91cc-9bb4405f98d1)

**Comment by m7pr** [comment]
It's a question on whether we use
````
teal.data::get_code(data, datanames = dataname_corrected_with_raw)
````
or
````
teal.data::get_code(data, datanames = dataname_corrected)
````
https://github.com/insightsengineering/teal/pull/1253/files#diff-4f959897d64b51a6ac57c9016430bdd92163a17fa62b5a61707a4b3bc7dd6325R42-R60

**Comment by m7pr** [comment]
As @gogonzo mentioned

> this is intentional. data sent to module contain ._raw_ datasets. And everything which is in the qenv needs to have a code.

**Comment by gogonzo** [comment]
I think we can close it or we can discuss is not too ugly and unique enough to make sure that user won't create this oneself (if app developer creates `_raw`, then it will be hard to detect which _raw has been created by teal and which by app developer). WDYT @m7pr  @vedhav @averissimo

**Comment by vedhav** [comment]
I am okay with having this on the reproducible code chunk. It provides a checkpoint where data is not filtered/transformed and this can be helpful. I'm also okay with `._raw_`.

**Comment by averissimo** [comment]
Agree. We can close this for now.
