### ISSUE TITLE
Resolve all "TODO:" in the codebase

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal#1312]
Follow-up on: https://github.com/insightsengineering/teal/pull/1253

Resolve all "TODO:" 
* inline comments: https://github.com/search?q=repo%3Ainsightsengineering%2Fteal+todo+path%3A%2F%5ER%5C%2F%2F&type=code
* test skips: https://github.com/search?q=repo%3Ainsightsengineering%2Fteal%20skip(%22todo%22)&type=code

Apparently, all of them has been introduced in the aforementioned PR

**Comment by donyunardi** [comment]
As discussed, we can remove the todo's comment under the R folder as pointed in the inline comments.

### Acceptance Criteria
* Add unit test which was previously marked as to do.
* If module has duplicate labels, we need to make sure that the datasets are still being passed correctly.
* When we reload the data, the filters are remain the same from previous activities.
* teal doesn't fail when there's no datasets.
