### ISSUE TITLE
[Question]: Upload data in this teal package

### ISSUE THREAD

**Issue by botsp** [insightsengineering/teal#1340]
### What is your question?

I'm working on a Shiny app using Teal and need users to upload their own data files. I'm having trouble because Teal seems to require data during initialization. 

Has anyone managed to integrate a file upload feature with Teal? Any advice on how to dynamically load data into a Teal app?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Hi @botsp 

You need to use `teal_data_module()` to allow user to upload data in teal app.
Check out [this](https://github.com/insightsengineering/teal/issues/952#issuecomment-1885042838) reply for code example.

**Comment by botsp** [comment]
Thank you, It works well based on that example;
