### ISSUE TITLE
[Question]: How to load different `modules()` based on the uploaded dataset

### ISSUE THREAD

**Issue by botsp** [insightsengineering/teal#1345]
### What is your question?

Hi, Is it possible to dynamically load different `modules()` based on the uploaded datasets? For example, passing information from an `actionButton` to allow load `modules()` based on different conditions in `init(..module=)`, or passing information from `init(..data=)` to `init(..module=)` for use?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by botsp** [comment]
````
Error: Assertion on 'modules' failed: One of the following must apply:
 * checkmate::check_multi_class(modules): Must inherit from class
 * 'teal_modules'/'teal_module', but has classes 'reactiveExpr','reactive','function'
 * checkmate::check_list(modules): Must be of type 'list', not 'reactiveExpr/reactive/function'.
 ````

**Comment by donyunardi** [comment]
Hi @botsp 

I don't think it's possible to dynamically load different `modules()` based on the uploaded datasets since `module()` has to be defined during `init()`.

**Comment by botsp** [comment]
yeah, it defined some `checkmate::assert` to regulated the inputs; I should read the `teal` code in more detail and make some explorations.
