### ISSUE TITLE
[Bug]: functions in `data` raise warnings

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#1352]
### What happened?

When `data` contains a function, a warning is logged when running `init`:

```
[WARN] 2024-09-26 11:08:10.5918 pid:6800 token:[] teal In 'rlang::hash(list(data = data, modules = modules))': 'package:teal' may not be available when loading
```

A similar one is logged when the app is run:
```
[WARN] 2024-09-26 11:48:19.3963 pid:21388 token:[4e453302] teal In 'rlang::hash(data[[dataname]])': 'package:teal' may not be available when loading  
```

It looks like it's happening in `create_app_id`. I [modified the function](https://github.com/insightsengineering/teal/pull/1353) so that `data` is also passed through `defunction` and that removed the warning raised when running `init` but not the one raised when runninng the app.

<details> <summary> example app </summary>

```
devtools::load_all("teal")

options("teal.bs_theme" = bslib::bs_theme(version = "5"))

data <- teal_data() |>
  within(iris <- iris) |>
  within(foo <- function(x) cat("hello\n"))
modules <- modules(
  example_module()
)

app <- init(data = data, modules = modules)

runApp(app)
```

</details>

### Relevant log output

```R
> packageVersion("teal")
[1] '0.15.2.9064'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
Update: The second warning occurs in `calculate_hashes`.

**Comment by donyunardi** [comment]
With the improvements that we've done [here](https://github.com/insightsengineering/teal/pull/1342), we could prevent the function object to be returned from teal_data() by prefixing the object's name with a dot (`.`).

Once I changed `foo` to `.foo`, I no longer see the warning.

<img src="https://github.com/user-attachments/assets/179ef164-e71d-400e-8720-76e40f020f17" width="50%" height="50%" />

**Comment by chlebowa** [comment]
I hadn't noticed the change to the rules. I can't say I like it but I'll accept it.

However, if one leaves a function in on purpose, one will get the warnings so the problem remains.

**Comment by donyunardi** [comment]
> However, if one leaves a function in on purpose, one will get the warnings so the problem remains.

Fair point and I agree.
Thanks for raising the PR, we'll look into this.

**Comment by gogonzo** [comment]
**Acceptance criteria:**
- filter panel should ignore objects which are clearly unfilterable: currently all objects except data.frame, matrix, MAE
- summary table should list all datanames - filterable should have obs/subjects while unfilterable probably should be hidden in collapsible panel under summary-table.
