### ISSUE TITLE
Improve documentation on creating custom teal module

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#1356]
### Summary

We currently have an article on how to create custom teal module [here](https://insightsengineering.github.io/teal/latest-tag/articles/creating-custom-modules.html). However, I’m still receiving feedback from internal users about the difficulty in understanding the content of this vignette. 

While we provide a full code example on how to write a teal module, there isn’t much context explaining what the code does, leaving users to figure it out themselves. Another common issue I’ve heard is related to troubleshooting custom teal modules. While it’s easy to do this with `browser()`, explicitly mentioning it in the documentation would be helpful.

Let’s improve this documentation by providing a detailed step-by-step guide on building a teal module. We’ll focus on adding explanations alongside the code and include guidance on troubleshooting teal modules.

Personally, I really like the flow of explanation this topic in [our youtube video](https://youtu.be/N8ZamECICSI?t=1245&feature=shared). It would be great if we follow the same explanation style.

**Comment by donyunardi** [comment]
@kumamiao 
What are your thought on this?

**Comment by kumamiao** [comment]
Just spoke with Vincent on this yesterday as well, I agree that adding more explicit documentation on creating customized modules will be helpful for our users. I agree with adding explanations along side the code to make the code examples less intimidating and include guidance on troubleshooting, and like the idea of utilizing the previous video.

Besides mentioned above, a specific flow based on a pretty common use case would be easy-to-follow for app developers: I have a `ggplot` function that generates a static plot with certain features, how do I convert it into a teal module and what are the steps to follow? We could have an example plot function and then elaborate on how to convert this function to a module step by step: 1. how to convert it to a teal module function, i.e., adding the ui and server components 2. how to add the interactive component 3. how to add show R code 4. how to add it to reporter, etc.

**Comment by donyunardi** [comment]
Another topic that we have to include in the docs: functional subset for delayed data
https://github.com/insightsengineering/teal.goshawk/issues/301#issuecomment-2394517728

**Comment by donyunardi** [comment]
I asked teal assistant to help us build this.
What do you guys think? @gogonzo @kumamiao 

## Creating a Custom `teal` Module for Dynamic Histograms

In this guide, we will convert a simple histogram formula, `hist(dataset[, selected], las = 1)`, into a robust `teal` module. This module will allow users to dynamically select datasets and variables to create histograms within a `teal` application. We’ll discuss best practices, including setting up dynamic inputs, structuring server logic, and using the `teal_data` object effectively to ensure reactivity and reproducibility.

### 1. Understanding the Inputs and Requirements

When developing a custom `teal` module for visualizations, identify the primary inputs that users will interact with:
- **Dataset Input** (`dataset`): Allows users to select which dataset to explore. 
- **Variable Input** (`selected`): Allows users to choose a specific numeric variable from the chosen dataset, ensuring that only appropriate columns are available for plotting.

These inputs are dynamically populated based on the available datasets and variables, creating an intuitive and error-resistant user experience.

### 2. Setting Up the Module UI

The UI function defines the controls and display area for the histogram. For this module, we’ll use:
- **`selectInput` for Dataset**: Enables users to select a dataset from the list of available datasets.
- **`selectInput` for Variable**: Allows users to choose a numeric variable from the chosen dataset, dynamically filtering out any non-numeric columns.
- **`plotOutput` for Histogram**: Displays the histogram once both dataset and variable inputs are selected.

Here’s the code for the `histogram_module_ui` function:

```r
# UI function for the custom histogram module
histogram_module_ui <- function(id) {
  ns <- shiny::NS(id)
  shiny::tagList(
    shiny::selectInput(ns("dataset"), "Select Dataset", choices = NULL),
    shiny::selectInput(ns("variable"), "Select Variable", choices = NULL),
    shiny::plotOutput(ns("histogram_plot"))
  )
}
```

### 3. Leveraging the `teal_data` Object in Server Logic

The `teal_data` object provides a powerful and flexible way to manage data in `teal` applications. In this section, we’ll look at best practices for using `teal_data` in server logic and how to interact with it effectively.

#### A. **Understanding `teal_data` as a Reactive Object in Server Logic**

When used in the server logic of a `teal` module, the `teal_data` object becomes a **reactive data container**. This means that to access its contents, you need to call it like a function, using parentheses: `data()`. This syntax triggers reactivity, ensuring that the data within `teal_data` stays up-to-date with any filters or changes applied elsewhere in the application.

> **Note**: The `teal_data` object behaves as a reactive data container only in the **server logic**. If used outside the server (e.g., in the UI definition), it would not be reactive.

#### B. **Using `datanames()` to Access Dataset Names**

The `teal_data` object can contain multiple datasets. To retrieve the names of these datasets, use the `datanames()` function:
```r
datanames(data())
```
This will return a character vector of the dataset names contained in `teal_data`. You can then use these names to dynamically populate input controls, like a dataset selection dropdown.

#### C. **Accessing Specific Datasets with Double Brackets (`[[ ]])`**

To access an individual dataset from `teal_data`, use double brackets (`[[ ]]`) along with the dataset name. This allows you to extract the specific dataset as a data frame:
```r
data()[[input$dataset]]
```
Here, `input$dataset` represents the name of the dataset selected by the user. This syntax is highly flexible because it dynamically references whichever dataset the user has chosen. You can further subset or manipulate this extracted data frame as needed.

#### D. **Setting Up Server Logic Using `teal_data`**

With these concepts in mind, we can set up server logic to:
1. Populate dataset and variable selections dynamically.
2. Render a histogram based on the selected dataset and variable.

```r
# Server function for the custom histogram module
histogram_module_server <- function(id, data) {
  moduleServer(id, function(input, output, session) {
    
    # Update dataset choices based on available datasets in teal_data
    shiny::observe({
      shiny::updateSelectInput(
        session,
        "dataset",
        choices = teal.data::datanames(data())
      )
    })
    
    # Update variable choices based on selected dataset, only including numeric variables
    observeEvent(input$dataset, {
      req(input$dataset)  # Ensure dataset is selected
      numeric_vars <- names(data()[[input$dataset]])[sapply(data()[[input$dataset]], is.numeric)]
      shiny::updateSelectInput(session, "variable", choices = numeric_vars)
    })

    # Render the histogram plot
    output$histogram_plot <- shiny::renderPlot({
      req(input$dataset, input$variable)  # Ensure both dataset and variable are selected
      selected_data <- data()[[input$dataset]]
      
      # Generate histogram with improved parameters for readability
      hist(
        selected_data[[input$variable]],
        las = 1,                          # Orientation for axis labels
        main = paste("Histogram of", input$variable), # Dynamic title
        xlab = input$variable,            # Dynamic x-axis label
        col = "lightblue",                # Optional color for histogram
        border = "black"                  # Optional border color
      )
    })
  })
}
```

### 4. Creating the Custom Module Object

The `teal::module()` function allows you to encapsulate your UI and server logic into a `teal` module, making it reusable and ready to integrate into any `teal` application. By setting `datanames = "all"`, you give the module access to all datasets specified in the `teal_data` object.

```r
# Custom histogram module creation
create_histogram_module <- function(label = "Histogram Module") {
  teal::module(
    label = label,
    ui = histogram_module_ui,
    server = histogram_module_server,
    datanames = "all"
  )
}
```

### 5. Integrating the Module into a `teal` App

With the module set up, it can now be integrated into a `teal` app. We’ll use `teal::init()` to specify the datasets and modules used in the app, then run the app to test functionality.

```r
library(teal)

# Define datasets in `teal_data`
data_obj <- teal.data::teal_data(
  iris = iris,
  mtcars = mtcars
)

# Initialize the teal app
app <- teal::init(
  data = data_obj,
  modules = teal::modules(create_histogram_module())
)

# Run the app
if (interactive()) {
  shiny::shinyApp(ui = app$ui, server = app$server)
}
```

### Best Practices Recap

#### A. **Focus on Flexibility**  
   Allowing users to select datasets and numeric variables dynamically enhances flexibility. Ensuring that input updates are user-friendly and aligned with the data’s structure makes the module accessible and robust.

#### B. **Dynamic Filtering**  
   By filtering available variable options to only show numeric columns, you avoid errors and improve usability.

#### C. **Use of Reactive Expressions and Validations**  
   Reactive expressions ensure that the module automatically responds to user input, and `req()` prevents unnecessary processing when inputs are incomplete.

#### D. **Reproducibility with `teal_data`**  
   By using `teal_data` to manage datasets, you ensure that your data handling is reproducible across sessions. Functions like `within()` from `teal.code` can encapsulate code changes for tracking and reproducibility, an essential feature for exploratory data analysis.

### Summary

Following these best practices, we’ve created a flexible, user-friendly `teal` module for histogram visualizations. This module not only allows for dynamic user input but is also built with a focus on modularity, robustness, and reproducibility. Users can adapt this framework for additional functionality (e.g., custom color schemes, bin sizes) as needed, with a foundation that supports easy integration and error handling.

**Comment by donyunardi** [comment]
Just conversed with the bot again to provide more accurate response, including the code reproducibility aspect of teal as example. I updated the last comment to reflect this.

**Comment by m7pr** [comment]
I think you should prepare a file under which we could comment
