### ISSUE TITLE
Modify print of `modules/module` to contain more information

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#1378]
Following should print the modules labels and their properties:

```r
print(modules, what = c("datanames", "bookmarkable")
```

This is needed because printed `modules` gives no clue about where to set or exclude some datanames. It is hard to determine before running an app what will be displayed where

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Enhance or rxtend 
* Needs to print characteristic of module
  * ui_args
  * server_args
  * datanames
  * filters
  * transformers
