### ISSUE TITLE
Warn when data contains an object named "all"

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#1379]
Because "all" is a reserved word in `module()`, otherwise this would be ambiguous.

**Comment by donyunardi** [comment]
We try to prevent the confusion when module(datanames = "all") 

### Acceptance Criteria
* teal should give a warning if there's an object in teal_data with name "all"
* the app should still continue (currently it failed when teal_data has object name "all")

**Comment by averissimo** [comment]
Teal is crashing with `all`. It seems related to lockfile generation 

Running `options("teal.lockfile.mode" = "disabled")` before the code below allows the example module to work

```r
data <- teal_data() |>
  within({
    all <- iris
  })

# data <- teal_data_module(
#   ui = function(id) {
#     ns <- NS(id)
#     actionButton(ns("submit"), label = "Load data")
#   },
#   server = function(id) {
#     moduleServer(id, function(input, output, session) {
#       eventReactive(input$submit, {
#         data <- within(
#           teal_data(),
#           {
#             all <- iris
#           }
#         )
#         data
#       })
#     })
#   }
# )


app <- init(
  data = data,
  modules = modules(
    example_module("Module with transformations 1", datanames = "all")
  ),
  title = "yada"
)

shinyApp(app$ui, app$server)
```

**Comment by gogonzo** [comment]
Works for me ;]

<img width="1463" alt="image" src="https://github.com/user-attachments/assets/0a1ece6b-cb4d-4cb3-8e22-c2484da48fdc">

<img width="1460" alt="image" src="https://github.com/user-attachments/assets/11357cfb-d527-43cf-9566-df557e48d4e3">

**Comment by averissimo** [comment]
Works after updating renv to `v1.0.11` :+1:

**Comment by averissimo** [comment]
`.raw_data` should also be considered a reserved word as it is being overwritten in the code.

```r
pkgload::load_all("teal")
data <- teal_data() |>
  within({
    all <- iris
    .raw_data <- mtcars
  })

app <- init(
  data = data,
  modules = example_module("Module with transformations 1", datanames = "all")
)
shiny::runApp(app)
```

![image](https://github.com/user-attachments/assets/b3254329-b4bb-45b6-aae4-1c0f87be5e11)

![image](https://github.com/user-attachments/assets/f52d656a-5fb1-4141-b3ef-d07516166ded)
