### ISSUE TITLE
Review Deprecated Functions

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#1386]
### Summary

Let's review the functions we deprecated in the previous release and decide whether to hard deprecate them (`lifecycle::deprecate_stop`) or remove them from the codebase entirely.

| Function | Action |
| --- | --- |
| hard deprecate on [TealData](https://github.com/insightsengineering/teal/blob/9c183f8c474698e20ec5842299cc8e189c28e7ee/R/init.R#L106-L115) | Remove |
| datasets argument in [ui](https://github.com/insightsengineering/teal/blob/9c183f8c474698e20ec5842299cc8e189c28e7ee/R/modules.R#L213-L220) and [srv](https://github.com/insightsengineering/teal/blob/9c183f8c474698e20ec5842299cc8e189c28e7ee/R/modules.R#L192-L199) formals in `module()`| Remove |

**Comment by m7pr** [comment]
Hey @donyunardi and @llrs-roche the same question as in teal.slice https://github.com/insightsengineering/teal.slice/issues/623#issuecomment-2472783188

Should we revisit `lifecycle::badge("experimental")` and `lifecycle::badge("stable")`

**Comment by llrs-roche** [comment]
There are 7 experimental features and 10 stable:
- Experimental:
 - Functions: 6
 - Argument: 1
- stable:
 - Functions: 10
 - Argument: 0

Also 2 deprecated and 1 superseded function.
