### ISSUE TITLE
One example on the decorator vingette doesn't work locally

### ISSUE THREAD

**Issue by llrs-roche** [insightsengineering/teal#1424]
The interactive-from lang example doesn't change the axis labels (on current branch status): 

https://github.com/user-attachments/assets/703cb08b-f581-40d0-ba6f-06e0b9e89a78

The `interactive_decorator_lang` decorator uses `make_teal_transform_server` which is also used by `static_decorator` ( used in no-ui tab example) but on that example there is no possible change on the axis by the app user. 

Other examples showing how to use decorators to change the axis interactively via function or with an interactive decorator work though.

My current understanding is that at [1187_decorate_output%40main/R/module_transform_data.R#L96](https://github.com/insightsengineering/teal/blob/1187_decorate_output%40main/R/module_transform_data.R?rgh-link-date=2024-11-22T14%3A09%3A55Z#L96) the teal_data has already the new x_axis_title (on third or fourth pass). 

I think that [make_teal_transform_server() ](https://github.com/insightsengineering/teal/blob/347b82a5246b1d2cc31b453de58c38cd8328b042/R/teal_transform_module.R#L193) seems to be run only once, instead of react to different input.

_Originally posted by @llrs-roche in https://github.com/insightsengineering/teal/pull/1357#discussion_r1853745262_

**Comment by m7pr** [comment]
@llrs-roche would you be able to verify now, after this commit was provided in the feature branch? 
https://github.com/insightsengineering/teal/pull/1357/commits/6c353fe697f19a485ce8fdec528ee7a790fd4e2b

**Comment by llrs-roche** [comment]
Yes fixed now. 

https://github.com/user-attachments/assets/0e532abf-33e2-40b9-885f-b462fb895352

**Comment by m7pr** [comment]
🔥 
great job @averissimo and thanks @llrs-roche for reporting and double checking
