### ISSUE TITLE
Visualization settings: capturing provenance: filters and encodings

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/teal#549]
**Summary**
Thought tan issue like this for teal already existed. couldn't find it so bringing back to life.
Capture filter & encoding settings to be able to display with visualization in footnote or somehow be able to maintain that with visualizations being used in presentations etc. for provenance,

What's the problem this feature will solve?
stakeholders request to maintain provenance of visualization settings beyond just having R code if desired.

What are you trying to do, that you are unable to achieve
with this package as it currently stands?
See previous answer

* Provide examples of real-world use cases that this would enable
and how it solves the problem you described.
During presentations that include visualizations generated from teal apps, scientists would be able to easily reference provenance info to further discuss the visualization and interpretation

* How do you solve this now?
I suppose it's solved for technical folks by generating the R code that produced the visualization but this does not work for non-technical users of our toolkit. scientists in particular and leadership audiences.

* Have you tried to work around the problem using other tools?
Nope

* Could there be a different approach to solving this issue?
--> Currently aside from doing this manually which is not going to fly, I don't know of a different approach other than to automatically capture the UI objects and their settings. Was thinking that like the Show R Code and Debug buttons there could be a "Visualization Settings" button that displayed a list in a modal like the "Show R Code". The user could then copy to clipboard and use it as they would like.

As a [persona], I [want to], [so that].
See previous answers

**Additional Information**

**Comment by nikolas-burkoff** [comment]
It's worth having a look at https://github.com/insightsengineering/teal.modules.clinical/pull/518 to see the sort of thing we're able to do now - this is a first pass at some of the tmc modules and we expectplenty of feedback but hopefully will capture what you are trying to do here

**Comment by nikolas-burkoff** [comment]
@npaszty lets  close this now that reporting is being rolled out into all the modules? And any other things needed could be issues in teal.reporter/ the teal.modules.x packages?

**Comment by donyunardi** [comment]
Closing.
