### ISSUE TITLE
Make `teal` with no modules

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal#622]
For multiple reasons, it would be beneficial to let users launch an application without any modules, i.e.:
```r
teal::init(data = teal.data::dataset("iris", iris), modules = list())
```
Reasons:
* for debugging the data
* examples could be condensed (no need to specify `example_module()` everywhere

It is also an opportunity to make the "blank page" have something useful.

**Comment by gogonzo** [comment]
Not required. One can run using 
```
teal::init(data = list(iris = iris), modules = list(module())) |> shiny::runApp()
```
