### ISSUE TITLE
Research - Make a chevron teal module

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#628]
Followup after meeting regarding making teal modules based on the chevron functions. This comment contains all propositions and will be updated each time we find something more. 

Initially, three options.

## 1. Shiny module on the fly

Advantage:
- full control over creating a module.
- Doesn't require teal nor chevron to make any changes.
- If it's a simple input-to-argument process, modules are relatively simple

Disadvantage:
- App developer must know shiny and how to make a teal module
- For more complicated apps these modules might take some significant space in preprocessing code

```r
aet_01_ui <- function(id) {
  div(
    numericInput("study", 1:10),
    selectInput("aval", c("a", "b", "c")),
    selectInput("strata", c("a", "b", "c")),
    ...
  )
}
aet_01_srv <- function(input, output, session) {
  validate(need(input$studyid), "You must select study!")
  
  chevron::aet_01(study = input$study, aval = input$aval, strata = input$strata, ...)
}

teal::module(aet_01_ui("<id>"), aet_01_srv("<id>"))
```

## 2. Module settings

(1) could be simplified only to the ui inputs which names would be equivalents of the tlg arguments.

Advantages:
- almost full control over inputs
- App developer will have to specify ui module and call tm_chevron_srv with chevron function
- Doesn't require teal nor chevron to make any changes.
- Could be an addition to (1). Sometimes could be just ui and universal tm_chevron_srv and sometimes app developer would create own server.

Disadvantages:
- Doesn't give a full control over what goes to the tlg. Does not give an option for validation.

```r
# this guy would be in teal
tm_chevron_srv <- function(input, output, session, ...) {
  # ... for static values/arguments
  do.call(aet_01, shiny::reactiveValuesToList(input))
}

# app dev should do following
aet_01_ui <- function(id) {
  div(
    numericInput("study", 1:10),
    selectInput("aval", c("a", "b", "c")),
    selectInput("strata", c("a", "b", "c")),
    ...
  )
}

teal::module(aet_01_ui("<id>"), tm_chevron_srv("<id>"))
# or simpler
tm_chevron("<id>", aet_01_ui)

```

## 3. Automatic deduction 

tm_chevron would somehow create ui and server for the tlg basing on it's arguments and possibly some additional instructions. Options does not exclude (1) nor (2) - they can be used interchangeably.

Advantages:
- Simplest for the app developer.
- concise code

Disadvantages:
- Whole burden on the teal which should guess which arguments needs what input
- S3 (normal R functions) does not share information about type of the argument so teal won't guess what is needed. Probably need to rewrite tlgs to S4
- Some additional instructions would be required anyway to at least point which arguments need shiny input and which needs static value.
- No control over shiny inputs, no meaningful validation

```r
tm_chevron(aet_01, <some custom settings>)
```

**Comment by kumamiao** [comment]
Update: chevron_to_teal will be positioned as a tool designed for standard output review/comment/communication by the study team. Please see the updated proposal here: https://docs.google.com/document/d/1wOLjq-uquMIVty_MsV9yCYgkd2W1mLYBiGnKADcwa7A/edit#
