### ISSUE TITLE
Remove dependency of get_rcode_srv on chunks and FIlteredData

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#633]
get_rcode_srv should be independent and expect (?? reactive) expression. This means that entire module expression should be joined before get_rcode_srv. 
Because `datasets`  argument should be deprecated first and chunks also might be used somewhere by some users I suggest to make a new `show_rcode_srv` module to print R code and replace `get_rcode_srv` -> `show_rcode_srv` it in all repos.

See the how the chunks are passed to the module to understand how important it is.
https://github.com/insightsengineering/teal/blob/e7d4e409ccea54a9e9688a33019021e4d0b99ac5/R/get_rcode.R#L235

**Comment by nikolas-burkoff** [comment]
@donyunardi  this can be closed as get_rcode_srv is being deprecated
