### ISSUE TITLE
Deprecate get_rcode_srv

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#640]
Will be replaced by [more generic module](https://github.com/insightsengineering/teal.widgets/issues/30) - not dependent on chunks, datasets etc.

Blocked directly by:
- https://github.com/insightsengineering/teal.modules.general/issues/388
- https://github.com/insightsengineering/teal.modules.clinical/issues/479
- https://github.com/insightsengineering/teal.goshawk/issues/146
- https://github.com/insightsengineering/teal.osprey/issues/141

**Comment by nikolas-burkoff** [comment]
This is closed on the 26chunks@main branch [here](https://github.com/insightsengineering/teal/pull/721)
