### ISSUE TITLE
Deprecate `datasets` in teal

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#656]
When calling teal_module which has a `datasets` argument we should throw deprecation message suggesting to use `data` and `filter_panel_api` separately.

Blocked by:
- https://github.com/insightsengineering/teal/issues/654
- https://github.com/insightsengineering/teal.slice/issues/64

**Comment by pawelru** [comment]
Hi @gogonzo is this still applicable?

**Comment by gogonzo** [comment]
Thanks, I need to close this 👍
