### ISSUE TITLE
Clicking on the hamburger icon when `filters = NULL` in `module()` shows empty space

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal#664]
`tm_file_viewer` uses the hamburger icon for the `Filter Panel` except that when clicked it unfolds empty space. Looks silly.

Filter panel turned on:
![image](https://user-images.githubusercontent.com/24480246/172446777-3e14686f-6730-4624-bc86-76d600c3c94f.png)

Filter Panel turned off:
![image](https://user-images.githubusercontent.com/24480246/172446858-21058a2b-16ec-411b-b69b-6b750d774a5b.png)

**Comment by gogonzo** [comment]
Done already
