### ISSUE TITLE
[User feedback] Provide more clear guidance on installation in Readme

### ISSUE THREAD

**Issue by kumamiao** [insightsengineering/teal#668]
- [ ] teal.reporter https://github.com/insightsengineering/teal.reporter/pull/102 and https://github.com/insightsengineering/teal.reporter/pull/109/
- [ ] teal.logger https://github.com/insightsengineering/teal.logger/pull/24 and https://github.com/insightsengineering/teal.logger/pull/25
- [ ] teal.widgets https://github.com/insightsengineering/teal.widgets/pull/64
- [ ] teal.slice https://github.com/insightsengineering/teal.slice/pull/66
- [ ] teal.data  https://github.com/insightsengineering/teal.data/pull/79 and then https://github.com/insightsengineering/teal.data/pull/83
- [ ] teal.transform https://github.com/insightsengineering/teal.transform/pull/80
- [ ] teal.code https://github.com/insightsengineering/teal.code/pull/50
- [ ] teal https://github.com/insightsengineering/teal/pull/684
- [ ] tmg https://github.com/insightsengineering/teal.modules.general/pull/425
- [ ] tmc https://github.com/insightsengineering/teal.modules.clinical/pull/531
- [ ] osprey https://github.com/insightsengineering/osprey/pull/89/
- [ ] teal.osprey https://github.com/insightsengineering/teal.osprey/pull/159
- [ ] goshawk https://github.com/insightsengineering/goshawk/pull/162
- [ ] teal.goshawk https://github.com/insightsengineering/teal.goshawk/pull/166
- [ ] tmh - is hermes on bioconductor now? https://github.com/insightsengineering/teal.modules.hermes/pull/262
- [ ] scda https://github.com/insightsengineering/scda/pull/88
- [ ] scda.2021 https://github.com/insightsengineering/scda.2021/pull/83
- [ ] scda.2022 https://github.com/insightsengineering/scda.2022/pull/55
- [ ] tern https://github.com/insightsengineering/tern/pull/629
- [ ] tern.mmrm https://github.com/insightsengineering/tern.mmrm/pull/88
- [ ] tern.rbmi (note not in last release) https://github.com/insightsengineering/tern.rbmi/pull/34
- [ ] nestcolor ((note not in last release) https://github.com/insightsengineering/nestcolor/pull/13
------------------------------

@wangh107 

By directly following the installation in the Readme page, installing `teal` would give the following error:
`ERROR: dependencies ‘teal.data’, ‘teal.logger’, ‘teal.widgets’ are not available for package ‘teal.slice’`

This issue: it would be good to add some notes about dependencies like in `teal.slice` Readme

For future, wondering if we could start to think if users could install nest as a whole like tidyverse

**Comment by nikolas-burkoff** [comment]
We could add in:

You might need to manually install all of the package dependencies before installing this package as without the dependencies = FALSE argument to install_github it may produce an error.

As this is shown in (hopefully) all the other repos with NEST dependencies

**Comment by kpagacz** [comment]
I see our READMEs suggest this:
![image](https://user-images.githubusercontent.com/24480246/175321789-715a5dcc-89bd-4045-9387-e3542821be35.png)

The problem here is `dependencies = FALSE` (thankfully missing from the `teal` README). For now, as we do not have any public repository for our packages that causes these problems.

@dinakar29 is working asap to put our packages somewhere public. Depending on how long it takes, we might want to think about changing the DESCRIPTION files to point to our public `github` repos as a dependency so users can get a working installation.

**Comment by gogonzo** [comment]
Please check if including `remotes` information in the description can help also

**Comment by dinakar29** [comment]
Add `Remotes` will help publish to https://pharmaverse.r-universe.dev/ui#packages
This can host the most recent version of packages. Packages are built every 60 minutes and published there.

**Comment by dinakar29** [comment]
We also had a discussion today, as a long term goal, to publish all public Github NEST packages to CRAN. More on that soon.
June release is available here publicly: https://github.com/insightsengineering/depository, but not a sustainable solutions.
