### ISSUE TITLE
Error in get: object 'filtered_data_new' not found

### ISSUE THREAD

**Issue by Mia-data** [insightsengineering/teal#673]
### What is your question?

I tried to run simple teal app example from https://insightsengineering.github.io/teal/articles/teal.html but I am getting an error "Error in get: object 'filtered_data_new' not found". How this could be solved? Am I missing any teal-related packages?

----------------------------------------------------
#>First, I've installed:
----------------------------------------------------
devtools::install_github("insightsengineering/teal.logger")
devtools::install_github("insightsengineering/teal.data")
devtools::install_github("insightsengineering/teal.widgets")
devtools::install_github("insightsengineering/teal.code")
devtools::install_github("insightsengineering/teal.slice")
devtools::install_github("insightsengineering/teal.reporter")
devtools::install_github("insightsengineering/teal.transform")
devtools::install_github("insightsengineering/teal@*release")

----------------------------------------------------
#>Then I run this code
----------------------------------------------------
library(teal)
app <- init(
  data = teal_data(
    dataset("IRIS", iris),
    dataset("MTCARS", mtcars)
  ),
  modules = modules(example_module()),
  header = "My first teal application"
)

if (interactive()) {
  runApp(app)
}

----------------------------------------------------
#>And get the error message
----------------------------------------------------
Listening on http://127.0.0.1:4262
Warning: Error in get: object 'filtered_data_new' not found
  1: runApp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by nikolas-burkoff** [comment]
Hi @Mia-data  - can you try installing the dependencies using "@release" as well for example:

```
devtools::install_github("insightsengineering/teal.data@*release")
```

Does that work?

**Comment by dinakar29** [comment]
Yes, alternatively, to pin to the last stable release of `teal`, this should work as well:

```R
devtools::install_github("insightsengineering/teal.logger@2022_06_09")
devtools::install_github("insightsengineering/teal.data@2022_06_09")
devtools::install_github("insightsengineering/teal.widgets@2022_06_09")
devtools::install_github("insightsengineering/teal.code@2022_06_09")
devtools::install_github("insightsengineering/teal.slice@2022_06_09")
devtools::install_github("insightsengineering/teal.reporter@2022_06_09")
devtools::install_github("insightsengineering/teal.transform@2022_06_09")
devtools::install_github("insightsengineering/teal@2022_06_09")
```

**Comment by Mia-data** [comment]
It works! Thank you for help!

**Comment by nikolas-burkoff** [comment]
Great that it works 👍 

> P.S. Maybe you could update installation note for other, future users by listing all of the above packages with release date in the note?

Yup we're in the process of making it easier to install the packages at the moment and we'll make sure that we update the README
