### ISSUE TITLE
tm_outliers: filter_spec defaults when adding a filter in the filter panel

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal#676]
### What happened?

Using the `main` branches, run the code below an reproduce the following steps:
1) Change the categortical variable to `SEX`.
2) Add a filter `SEX` in the filter panel.
3) The categotical variable filter defaults as below:
![Screenshot from 2022-06-27 10-38-48](https://user-images.githubusercontent.com/86970066/175897171-72c3ba5c-e56d-4104-bde1-1aebc30cc422.png)

```
library(scda)
ADSL <- synthetic_cdisc_data("latest")$adsl

fact_vars_adsl <- names(Filter(isTRUE, sapply(ADSL, is.factor)))
vars <- choices_selected(variable_choices(ADSL, fact_vars_adsl))

app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", ADSL, code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"),
    check = TRUE
  ),
  modules = modules(
    tm_outliers(
      outlier_var = list(
        data_extract_spec(
          dataname = "ADSL",
          select = select_spec(
            label = "Select variable:",
            choices = variable_choices(ADSL, c("AGE", "BMRKR1")),
            selected = "AGE",
            multiple = FALSE,
            fixed = FALSE
          )
        )
      ),
      categorical_var = data_extract_spec(
        dataname = "ADSL",
        filter = filter_spec(
          vars = vars,
          choices = value_choices(ADSL, vars$selected),
          selected = value_choices(ADSL, vars$selected),
          multiple = TRUE
        )
      ),
      ggplot2_args = teal.widgets::ggplot2_args(labs = list(subtitle = "Plot generated by Outliers Module"))
    )
  )
)
shinyApp(app$ui, app$server)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Polkas** [comment]
So I find out the there is some reactivity from FilteredData, which cases the modules to be CREATED MANY 
TIMES from scratch. The fIlter_spec shows us a side effect of it, the filter was reinitialized each time.
We could play here with isolate, still out primary decision was to revert it in such case. 

I created a PR https://github.com/insightsengineering/teal/pull/677
