### ISSUE TITLE
add chunk option for preprocessing-data vignette

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#679]
https://github.com/insightsengineering/teal/blob/c499db19d5552b5aa17d70763e579d7ec0f74672/vignettes/preprocessing-data.Rmd#L25

This line of code is displaying the data of `synthetic_cdisc_data("latest")$adsl` which makes the the vignette page very long.

Should we add `eval=FALSE` for this chunk on line 21?
https://github.com/insightsengineering/teal/blob/c499db19d5552b5aa17d70763e579d7ec0f74672/vignettes/preprocessing-data.Rmd#L21-L25

and again on this chunk?
https://github.com/insightsengineering/teal/blob/c499db19d5552b5aa17d70763e579d7ec0f74672/vignettes/preprocessing-data.Rmd#L44-L48

If agree, I'd assign this issue to myself and fix this.

**Comment by nikolas-burkoff** [comment]
Closing this in favour of #700
