### ISSUE TITLE
Handling deparse in tests when using covr

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal#68]
<REDACTED>NEST/teal/issues/964#issuecomment-66284

<REDACTED>NEST/teal/pull/1018 but it should be handled more generally.

Clearly this is only adds value if we are consistently using covr in our pipelines and we find other cases which cause problems when improving our testing of teal

Provenance: 
```
Creator: burkoffn
```

**Comment by pawelru** [comment]
not an issue anymore - there is no occurrence of `deparse` in the tests
