### ISSUE TITLE
Update vignette

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal#682]
### Feature description

Update vignette after this PR https://github.com/insightsengineering/teal/pull/674#discussion_r910985650 to account for the changes in using `data` and `datasets` and to use quosures
```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.
```

**Comment by nikolas-burkoff** [comment]
Also update vignettes following https://github.com/insightsengineering/teal/pull/692

**Comment by nikolas-burkoff** [comment]
Blocked by https://github.com/insightsengineering/teal.slice/issues/76

**Comment by donyunardi** [comment]
Hi @nikolas-burkoff 
Are we okay to move forward considering the mentioned issues are now closed or do we still have a blocker?

**Comment by nikolas-burkoff** [comment]
So I can continue on this now - so I'll unblock the issue - though it should be merged in with or after https://github.com/insightsengineering/teal.code/pull/49 so I won't unblock the PR itself
