### ISSUE TITLE
SLOW Styling of the SHOW R CODE

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal#690]
https://github.com/insightsengineering/teal/blob/ef146cd0962a2d0ed6246174b47d091a7e6aa67d/R/get_rcode.R#L121

The slow styling of the r code was exposed when we applied teal.reporter in the goshawk app where there is a sufficient amount of the preprocessing code. For goshawk sample app the teal.reporter is at least x10 slower (when adding the card) than for tmc/tmg related ones (safety/efficacy/exploratory).
We have to think how we want to handle this problem. 
- We could add additional argument to the function and give the developer an option to turn off/on this styling. 
- Another connected problem is that the preprocessing code provided by the end user lose the formatting in teal::init to be once more formatted at the end.

@gogonzo I think this item is quite important.

**Comment by pawelru** [comment]
`profvis@1.8.0` (released in October so few months after your message) claims to be 40% faster:

https://github.com/r-lib/styler/blob/f8321047b5ff612e91b03812b4312c8af11a0a0d/NEWS.md?plain=1#L6-L9

Is this still an issue then?

**Comment by pawelru** [comment]
closing as not relevant anymore
