### ISSUE TITLE
[Question]: Example code error

### ISSUE THREAD

**Issue by La-May** [insightsengineering/teal#691]
### What is your question?

Thanks for the share! But I encountered a problem when I try to use it.
When I runned the example code about  teal package, I saw a error like this "Warning: Error in : 'validate_metadata' is not an exported object from 'namespace:teal.data'". 
And the example code is "
```r
library(teal)

app <- init(
  data = teal_data(
    dataset("IRIS", iris),
    dataset("MTCARS", mtcars)
  ),
  modules = modules(example_module()),
  header = "My first teal application"
)

if (interactive()) {
  runApp(app)
}
```
"
I would really appreciate your reply.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by La-May** [comment]
I installed the latest released version. But It seems that the released version didn't have the exported object written in the /namespace document.

**Comment by gogonzo** [comment]
Could you provide result of your `sessionInfo()`? We can help you then resolve this problem

**Comment by La-May** [comment]
> Also did you/can you try installing the June release following these instructions: https://github.com/insightsengineering/depository#readme
> 
> (The other way of installing the packages mentioned in the README will only work once the packages have next been released which is due mid August)

I have installed the newest version in git and it works! 
Thanks a lot for both of your help.😁
