### ISSUE TITLE
Teal/Teal.data vignette issues

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal#700]
We should review the teal and teal.data vignettes and fix them so that there is a coherent set of linked vignettes introducing the `data` argument of `teal::init` for new users of the framework  the links are [here](https://github.com/insightsengineering/teal.data/blob/4fcf323a568c548bd0589ea97bcf60fe3537105c/vignettes/teal-data.Rmd#L50) at the moment.

We could move all the vignettes into teal.data and from teal have a link to teal.data for people wanting to learn about the data argument in teal.init. Or we could leave the vignettes needed for teal::init in teal (reference them from teal.data) and then have only the more advanced vignettes in teal.data itself 

Note also there is work to make the teal and its vignettes work with `data` instead of `datasets` [here](https://github.com/insightsengineering/teal/issues/682) but that should not interfere with this issue

We should also fix the formatting and outputs - see the pkgdown website for example:
- Review each of `teal` vignettes and move the technical details to `teal.data` and keep only examples in `teal`:
- [x] processing data --> moved to `teal`
- [x] Input general data in a teal application -->  no change
- [x] Input ADaM data in a teal application -->  details on join_keys removed
- [x] Input MAE data in a teal application -->  no change
- [x] Join keys --> moved to teal
- [x] Creating custom modules -->  no change
- [x] Adding support for reporting to custom modules -->  no change
- [x] Modifying a teal application with R options -->  no change

Additional issues:
- [x] The "Input ADaM data in a teal application" proceeds to talk all about join_keys for general teal data?  

- [x] Things like this are not helpful:
![image](https://user-images.githubusercontent.com/15201933/179964722-7688a409-e5f3-441b-80c2-9c6292b4da4a.png)

- [x] Nor outputs like this:
![image](https://user-images.githubusercontent.com/15201933/179964838-baaf5cb3-431d-435d-b784-5050f6d890b9.png)
![image](https://user-images.githubusercontent.com/15201933/179964944-9d61676e-96c0-4955-b68c-1444fdb68a51.png)

**Comment by nikolas-burkoff** [comment]
See also https://github.com/insightsengineering/teal/issues/679

**Comment by mhallal1** [comment]
@nikolas-burkoff after spending some time trying to reason from a user's perspective, I would suggest the following:
-move the technical side of `teal.data` functions that are in `teal` vignettes to `teal.data` vignettes.
-Keep the actual `teal` vignettes and instead of explaining the details of the functionality, we could show the necessary functions needed from `teal.data` with an app example and refer to the `teal.data` vignettes for more explanation.
