### ISSUE TITLE
[Question]: <title>Custom modules in teal.

### ISSUE THREAD

**Issue by La-May** [insightsengineering/teal#707]
### What is your question?

Hi,

I am trying to custom 'tm_t_summary' module and have a problem that make me confused. 
For example, I wanna replace the label of 'min' from 'Minimum' to 'Min'. After I did the replacement in summarize_variable R file and renamed 'summarize_vars' to 'summarize_vars_', I have a bug in the RShiny app:
The following errors(s) occurred:

could not find function "summarize_vars_"
when evaluating the following code:
```
lyt <- rtables::basic_table(main_footer = "n represents the number of unique subject IDs such that the variable has non-NA values.") %>%
  split_cols_by("ARM") %>%
  add_overall_col("Total") %>%
  add_colcounts() %>%
  summarize_vars_(vars = structure(c(SEX = "SEX", RACE = "RACE", AGE = "AGE"), dataname = "ADSL", always_selected = character(0)), var_labels = c(SEX = "Sex", RACE = "Race", AGE = "Age"), show_labels = "visible", na.rm = TRUE, na_level = "<Missing>", denom = "N_col", .stats = c(
    "n", "mean",
    "sd", "median", "min", "max", "count_fraction"
  ))
```
And summarize_vars_ function has been created in the R_GlobalEnv.

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Hi @La-May 
In order to better help you, I'd need see what you wrote/updated so far so I can reproduce it.
Could you please provide this?

**Comment by La-May** [comment]
> Sure. There are just 3 simple changes.
I have edited the summary_label function in _summarize_variables.R_ downloaded from insightsengineering/tern.

summary_labels <- function() {
  c(
    mean = "Mean",
    sum = "Sum",
    sd = "SD",
    se = "SE",
    mean_sd = "Mean (SD)",
    median = "Median",
    mad = "Median Absolute Deviation",
    iqr = "IQR",
    range = "Min - Max",
    cv = "CV (%)",
  `  min = "Min", #'Changed from "Minimum"`
    max = "Maximum",
    geom_mean = "Geometric Mean",
    geom_cv = "CV % Geometric Mean",
    n = "n"
  )
}


#‘ Rename function
`summarize_vars_` <- function(lyt,
                           vars,
                           var_labels = vars,
                           nested = TRUE,
                           ...,
                           show_labels = "default",
                           table_names = vars,
                           .stats = c("n", "mean_sd", "median", "range", "count_fraction"),
                           .formats = NULL,
                           .labels = NULL,
                           .indent_mods = NULL) {
  afun <- create_afun_summary(.stats, .formats, .labels, .indent_mods)
  
  analyze(
    lyt = lyt,
    vars = vars,
    var_labels = var_labels,
    afun = afun,
    nested = nested,
    extra_args = list(...),
    inclNAs = TRUE,
    show_labels = show_labels,
    table_names = table_names
  )
}

> **Below is the corresponding change in  _tm_t_summary.R_ from teal,**

  layout_list <- add_expr(
    layout_list,
    if (length(var_labels) > 0) {
      substitute(
        expr = `summarize_vars_`(
          vars = sum_vars,
          var_labels = sum_var_labels,
          show_labels = show_labels,
          na.rm = na.rm,
          na_level = na_level,
          denom = denom,
          .stats = stats  
        ),
        env = env_sum_vars
      )
    } else {
      substitute(
        expr = `summarize_vars_`(
          vars = sum_vars,
          show_labels = show_labels,
          na.rm = na.rm,
          na_level = na_level,
          denom = denom,
          .stats = stats
        ),
        env = env_sum_vars
      )
    }
  )

>And the shiny app code.


app <- init(
  data = cdisc_data(
    cdisc_dataset("ADSL", adsl
    )
  ),
  modules = modules(
    tm_t_summary(
      label = "Demographic Table",
      dataname = "ADSL",
      # ARM,ARMCD can be selected  ,and ARM is pre-selected
      arm_var = choices_selected(c("ARM", "ARMCD"), "ARM"),
      summarize_vars = choices_selected(
        c("SEX", "RACE", "AGEGR1", "EOSSTT", "DCSREAS", "AGE"),
        c("SEX", "RACE", "AGE")
      ),
      add_total = TRUE,
      useNA = "no",
     numeric_stats = c("n", "mean", "sd","mean_ci", "median", "median_ci", "quantiles",
                         "min","max","geom_mean")
      ,pre_output = tags$h1("test-pre_output")
      ,post_output =shiny::helpText("test-post_output")
    )
  )
)
shinyApp(app$ui, app$server)

**Comment by La-May** [comment]
>I can just run R code cpyied from  "Show R code" panel.

ADSL_FILTERED <- ADSL



ANL_1 <- ADSL_FILTERED %>% dplyr::select(STUDYID, USUBJID, ARM, SEX, RACE, AGE)
ANL <- ANL_1
ANL <- ANL %>% formatters::var_relabel(AGE = "Age", SEX = "Sex", RACE = "Race")

ANL_ADSL_1 <- ADSL_FILTERED %>% dplyr::select(STUDYID, USUBJID, ARM)
ANL_ADSL <- ANL_ADSL_1

anl <- ANL %>% df_explicit_na(omit_columns = setdiff(names(ANL), c(structure(c(SEX = "SEX", RACE = "RACE", AGE = "AGE"), dataname = "ADSL", always_selected = character(0)))), na_level = "<Missing>")
anl <- anl %>% dplyr::mutate(ARM = droplevels(ARM))
arm_levels <- levels(anl[["ARM"]])
ANL_ADSL <- ANL_ADSL %>% dplyr::filter(ARM %in% arm_levels)
ANL_ADSL <- ANL_ADSL %>% dplyr::mutate(ARM = droplevels(ARM))
ANL_ADSL <- df_explicit_na(ANL_ADSL, na_level = "")
lyt <- rtables::basic_table(main_footer = "n represents the number of unique subject IDs such that the variable has non-NA values.") %>%
  rtables::split_cols_by("ARM") %>%
  rtables::add_overall_col("Total") %>%
  rtables::add_colcounts() %>%
  `summarize_vars_`(
    vars = structure(c(SEX = "SEX", RACE = "RACE", AGE = "AGE"), dataname = "ADSL", always_selected = character(0)), var_labels = c(SEX = "Sex", RACE = "Race", AGE = "Age"), show_labels = "visible", na.rm = TRUE, na_level = "<Missing>", denom = "N_col",
    .stats = c("n", "mean", "sd", "median", "min", "max", "count_fraction")
  )
result <- rtables::build_table(lyt = lyt, df = anl, alt_counts_df = ANL_ADSL)
result

**Comment by donyunardi** [comment]
Sorry, I still can't reproduce your error but I can mention couple things.

In `tern`, there's no easy way to change the label name from user's perspective (`summary_labels` is an internal function).  The quickest way to achieve what you want, for testing purposes only, is to rebuild the `tern` package after you change the `summary_labels`, and not change anything else. 
If you run your R code that contains`rtables` statements, you will see the updated label (I was able to see it).

In `teal.modules.clinical`, the `tm_t_summary` module, by default, provides several statictics for numeric variables, and range is one of them (with `Min-Max` label). Just remove/comment the `numeric_stats` argument from your shiny code to trigger the default behavior. Would this be sufficient? Individual row for Min/Max is not designed for this specific module.

**Comment by donyunardi** [comment]
Tagging @shajoezhu @gogonzo

**Comment by La-May** [comment]
Thanks a lot for your reply.
As I have mentioned above, after I changed the `summary_labels` function and renamed the `summarize_vars` function to `summarize_vars_`, it worked if I runned the R code contains rtables. That is really the one makes me confused because it will not work if invoke it in `tm_t_summary` module.
So to my understanding , there is no way for us to use the self-defined function in `tm_t_summary` module unless we rebuild the involved package `tern`?

**Comment by donyunardi** [comment]
Just to make sure I understand the process that you made:

1.  Downloaded two individual files from the repo:
    1.  summarize_variables.R (from tern)
    1.  tm_t_summary.R (from teal.modules.clinical)
1.  Made the changes that you mentioned before on these two files
1.  Run both files (in its entirety) in global environment
1.  Run `library(teal.modules.clinical)`

If so, then yes, I don't think it's possible to run the self-defined `tm_t_summary` function this way. The updated `tm_t_summary` (in global environment) will fail because of internal function dependencies.

**Comment by La-May** [comment]
Thank you very much for your kind reply. ^_^

The process is mostly right but I don't run `library(teal.modules.clinical)` at last. But I think I have get inofrmation I need and thanks again.

And there is another thing I want to know, is it possible that we custom a totally new module that can be used in teal::init?

**Comment by donyunardi** [comment]
Sure, happy to help! =)

You can visit this vignette on setting up custom module in teal:
https://insightsengineering.github.io/teal/main/articles/creating-custom-modules.html
