### ISSUE TITLE
Restructure vignettes

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal#708]
### Feature description

Restructure `teal` vignettes such that they represent a melting point for other `teal.XXX` packages.
The `teal` vignettes should point to other packages vignettes instead of repeating information.

```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.
```

**Comment by donyunardi** [comment]
We've done couple efforts around vignettes:
* https://github.com/insightsengineering/coredev-tasks/issues/468
* https://github.com/insightsengineering/coredev-tasks/issues/467

And we'll also try to do:
* https://github.com/insightsengineering/teal/issues/807

Therefore, I'm closing this issue. 
Please feel free to open a new issue for specific area of the vignette from `teal.xxx` package that you we think could be added to teal.
