### ISSUE TITLE
Research switch to bootstrap 4

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#709]
Please see @Polkas comment
https://github.com/insightsengineering/teal/issues/617

Scope:
- include BS4 source into teal or/and teal.widgets
- check what doesn't work and need fixes
- create the issue for each "BUG"

**Comment by Polkas** [comment]
Objective SUpport BS3 , BS4 and BS5 at the same time in the project.
- check the custom bootstrap related css rules (should not be many).
- tag hooks to achieve a dynamic render under different versions of bootstrap; rewrite the teal.widgets connected tools (what have to be rewritten)
- main fluidPage in the teal to inject the bootstrap theme; done with the additional option like https://github.com/insightsengineering/teal/blob/main/vignettes/teal-options.Rmd
- bslib package ...

Issues:

**Comment by Polkas** [comment]
for bivariate and variable_browser when bs_theme(version="3")

```

Listening on http://127.0.0.1:3630
Warning: Error in compile_data: Error: Undefined variable: "$secondary".
        on line 69:16 of ../../../../Library/Frameworks/R.framework/Versions/4.2/Resources/library/shinyWidgets/assets/bootstrap-switch/bootstrap-switch-3.4/bootstrap-switch.scss
        from line 11:9 of stdin
>> 			background: $secondary;

   ---------------^

  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
```

**Comment by Polkas** [comment]
with have 4 different bootstrap versions, NULL (default) and bslib 3, 4, 5 where NULL a 3 should be the same but have small differences.

Sample apps:

```
> knitr::kable(data.frame(app = teal.gallery::list_apps(), "NULL" = "", "3" = "", "4" = "", "5" = ""))


|app                     |NULL. |X3 |X4 |X5 |
|:-----------------------|:-----|:--|:--|:--|
|basic-teal              |      |   |   |   |
|CDSE-MAE-connector      |      |   |   |   |
|DataSetDB-MAE-connector |      |   |   |   |
|early-dev               |      |   |   |   |
|efficacy                |      |   |   |   |
|entimICE-DDL            |      |   |   |   |
|exploratory             |      |   |   |   |
|longitudinal            |      |   |   |   |
|patient-profile         |      |   |   |   |
|python                  |      |   |   |   |
|RNA-seq                 |      |   |   |   |
|safety                  |      |   |   |   |
```

**Comment by Polkas** [comment]
- [ ] https://github.com/insightsengineering/teal/pull/727
- [ ] https://github.com/insightsengineering/teal.reporter/pull/134
- [ ] https://github.com/insightsengineering/teal.widgets/pull/84
- [ ] https://github.com/insightsengineering/teal.modules.general/pull/454
- [ ] https://github.com/insightsengineering/teal.data/pull/100

**Comment by donyunardi** [comment]
When reading the vignette, I got this error message when trying out the example code for `run_with_themer`:

![image](https://user-images.githubusercontent.com/8597300/190049302-9fed9d99-0043-4d8d-bc5a-1c795c78f68e.png)

Is it because this line return NULL when it's expecting `bs_theme` object?
https://github.com/insightsengineering/teal/blob/94b793d17b7dde81a0742d8dd23e1d2a6e59fc34/R/module_teal.R#L94

sessionInfo:

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] teal_0.11.1.9023          teal.transform_0.1.1.9014 magrittr_2.0.3           
[4] teal.data_0.1.1.9013      shiny_1.7.2              

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3           rstudioapi_0.13        teal.logger_0.1.0.9014 xtable_1.8-4          
 [5] R6_2.5.1               rlang_1.0.3            fastmap_1.1.0          logger_0.2.2          
 [9] tools_4.2.1            checkmate_2.1.0        cli_3.3.0              jquerylib_0.1.4       
[13] htmltools_0.5.2        formatters_0.3.3.1     shinyjs_2.1.0          ellipsis_0.3.2        
[17] yaml_2.3.5             digest_0.6.29          fontawesome_0.3.0      lifecycle_1.0.1       
[21] crayon_1.5.1           later_1.3.0            sass_0.4.1             promises_1.2.0.1      
[25] memoise_2.0.1          cachem_1.0.6           glue_1.6.2             mime_0.12             
[29] bslib_0.4.0            compiler_4.2.1         backports_1.4.1        jsonlite_1.8.0        
[33] httpuv_1.6.5          
```

**Comment by donyunardi** [comment]
Quick glance every theme and it looks great!

I was reviewing `exploratory` app from teal.gallery with bs=5 theme, and there are couple things that I noticed:

### Module
----
In FileViewer, I see `Couldn't load plugin' message when I selected `pdf` encoding.

<img src="https://user-images.githubusercontent.com/8597300/190056138-86d6c3d3-dd37-4ed1-b0d1-c68796d76423.png" width="70%" height="70%" />

### Filter Panel
----
When deselecting all options, the selectizeInput size changes and it's hard to see the available selection to choose.

<img src="https://user-images.githubusercontent.com/8597300/190056334-dc955710-81bc-4549-be58-6abce46cf288.png" width="50%" height="50%" />

The blue background is not in the position with the selection.
<img src="https://user-images.githubusercontent.com/8597300/190056520-f759e98b-4430-4872-9f55-1a25057bd8a9.png" width="50%" height="50%" />

Dataset name is not in bold red.
There is no padding between filter category.

<img src="https://user-images.githubusercontent.com/8597300/190056915-764f1634-c7e3-4989-93cd-87ba49c0e58d.jpg" width="50%" height="50%" />

### Encoding
----
The selectInput box is either transparent or has the same color with background
The font color for dataset name (i.e. `ADSL`)is not red.
The `Dataset` field is not on a new line.

<img src="https://user-images.githubusercontent.com/8597300/190057421-412f2e8c-7d23-4bb3-bf4e-6120a8707158.jpg" width="50%" height="50%" />

I'm not sure if these are all just side-effect of new bs theme or if this teal's css related.

**Comment by Polkas** [comment]
@dony just fix the example in the vignette, The interactive theming for Bootstrap 3 isn't supported, I added the options() call at the top of this example.However if you use e.g. bslib::bs_theme(version = "3", bootswatch = "superhero")  it will work, so only for interactive mode.

**Comment by Polkas** [comment]
All of the items have to be investigated.
I do not now yet how many of them I will solve that is why I still not created issues.
1. Select Input problem - it is because of our custom css as we do not want to have wide options area https://github.com/insightsengineering/teal.widgets/pull/84/files#diff-9967989e616e1e5498f6d3ade28640c5e9f506515ff6fad19b945c7ff1536d56
2. I added a temporary fix there, there bars area cover the checkboxes and they could not be clicked before. This have to be improved. It is a problem only for bootstrap 5, how it handles relative position.
3. Sth new for me
4. I see it but it is a problem only for the default theme

**Comment by donyunardi** [comment]
Just want to add that the FileViewer module, the pdf view part, runs smoothly once I run the app in regular browser.
Thanks for the suggestion!
