### ISSUE TITLE
vignette typo

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#715]
Should be `hermes`.

https://github.com/insightsengineering/teal/blob/27eb96ab8b12938119af08ab2eb60d588e0c425b/vignettes/including-mae-data-in-teal.Rmd#L40

**Comment by nikolas-burkoff** [comment]
For something like this - it's going to be more efficient to just open the PR to fix it rather than having it as a separate issue?

**Comment by donyunardi** [comment]
Agree! I will do this moving forward.
