### ISSUE TITLE
Merge the refactor branch

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal#731]
Closed when the following are merged.

See https://github.com/insightsengineering/NEST-roadmap/issues/69 for more details and what else needs to be done as part of the refactor

- [x] https://github.com/insightsengineering/teal.code/pull/66 @nikolas-burkoff @donyunardi 
- [x] https://github.com/insightsengineering/teal/pull/768 @nikolas-burkoff @asbates @donyunardi
-----
- [x] https://github.com/insightsengineering/teal.modules.general/pull/485 @donyunardi 
- [x] https://github.com/insightsengineering/teal.modules.clinical/pull/598 @BLAZEWIM [668](https://github.com/insightsengineering/teal.modules.clinical/issues/668) [670](https://github.com/insightsengineering/teal.modules.clinical/issues/670)
- [x] https://github.com/insightsengineering/teal.goshawk/pull/203 @gogonzo 
- [x] https://github.com/insightsengineering/teal.osprey/pull/192 @nikolas-burkoff 
- [x] https://github.com/insightsengineering/teal.modules.helios/pull/34  @nikolas-burkoff 
- [x] https://github.com/insightsengineering/teal.modules.hermes/pull/294 @nikolas-burkoff 

Key things to check:
1) The modules and sample apps still work:
  - the SRC shows the code needed to generate the output (play with the filter panel and encodings and make sure that changes are reflected in the code).
  - the warnings and error handling works smoothly
  - confirm we don't have a performance hit moving to qenv
2) The docs in teal.code and teal are clear - if not then please improve them!

Be aware that there are things still be done after the merge - see roadmap issue linked above - so when testing check if issue is already there first and if you do create a new issue then please add it to the roadmap issue

**Comment by donyunardi** [comment]
>  choose name of data class (for now this could live in teal but will be moved to teal.data so maybe best to have it there) and add getter for join_keys and get_ code

naming ideas for data class:
* datalink
* dataport
* dataenv / envdata
* dataclass
* datacontainer
* dataservice
* datasync
