### ISSUE TITLE
Add `isolate` when `data[[...]]()` is used in a UI function so modules can be used outside of `teal::init`

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal#743]
From [here](https://github.com/insightsengineering/teal.modules.general/pull/462#issuecomment-1254762760)

This app works (on teal_refactor@main if not yet merged in) but only because of e.g. [here](https://github.com/insightsengineering/teal.modules.general/blob/teal_refactor%40main/R/tm_data_table.R#L139) - this should be done throughout the code base and docs updated in teal for creating your own modules.

![image](https://user-images.githubusercontent.com/15201933/191710324-74d74ccd-59e8-44d3-8b1b-cb0e287640ca.png)

```
library(teal.modules.general)
library(shiny)

data <- new_tdata(list(iris = iris))

var_brow <- tm_variable_browser()
dat_tab <- tm_data_table()

ui <- fluidPage(
  fluidRow(
    column(8, do.call(var_brow$ui, c(list(id = "id_1", data = data), var_brow$ui_args))),
    column(4, do.call(dat_tab$ui, c(list(id = "id_2", data = data), dat_tab$ui_args)))
  )
)

server <- function(input, output, session) {
  do.call(var_brow$server, c(list("id_1", data = data), var_brow$server_args))
  do.call(dat_tab$server, c(list("id_2", data = data), dat_tab$server_args))
}

shinyApp(ui, server)
```

A separate issue could be created to simplify calling modules outside of teal as the above is clunky

**Comment by donyunardi** [comment]
### Definition of Done
Implement `dataset <- isolate(data[[x]]())` to all UI function in modules packages.

**Comment by nikolas-burkoff** [comment]
Closing this as the only modules throughout the codebase which have data in the ui function are 
- variable_browser already fixed
- datatable already fixed
- missing data - does not need fixing as only names(data) is used not data[[...]]()
