### ISSUE TITLE
Deprecate merge_expression

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal#744]
While UATing the NEWS, an entry reports that: 
_Deprecated `merge_expression` argument in `get_rcode_srv` and `get_rcode` has been removed._

Checking the code base, `merge_expression` is removed completely in `get_rcode_srv` and not deprecated. Check if this needs to be deprecated or it can stay as it is and update the NEWS entry accordingly.

Originial issue: https://github.com/insightsengineering/teal/pull/674/files

**Comment by donyunardi** [comment]
I think you're right, it looks like we removed the argument without going through deprecation cycle.
At this point, I'd just update the NEWS entry accordingly.

**Comment by gogonzo** [comment]
It was deprecated for 2 years. get_rcode was initially in the teal.devel where `merge_expression` was deprecated
https://github.com/insightsengineering/teal.devel/blob/4f2dc19407d9a65aa37da224b8d7c3e684330509/R/get_rcode.R#L70

In teal latest release it was also deprecated
https://github.com/insightsengineering/teal/blob/7a87d3b7fdcd349f24c23cb24e17a414a192e533/R/get_rcode.R#L70
