### ISSUE TITLE
active filter drilldown

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#747]
### Feature description

When multiple filters are set up for one dataset, each filter presents value ranges or counts of factor values, let's call them "options" generally. Now, when one filter is applied, the options in the remaining filters should change to reflect the remaining observations. Currently, all filter choices are created from the entire dataset.

For example:

```
MTCARS
cyl
v 4 (11)
v 6 (7)
v 8 (14)

vs
v 0 (18)
v 1 (14)
```

and then

```
MTCARS
cyl
v 4 (11)
v 6 (7)
v 8 (14)

vs
o 0 (18)
v 1 (14)
```

The numbers in `cyl` should add up to 14, not 32.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Your observation is correct and we have included this scope on this our redesign filter panel discussion here:
https://github.com/insightsengineering/teal.slice/issues/47#issuecomment-1238099857

The topic about updating the "options" count is at the bottom of this comment.

Closing as duplicate.
