### ISSUE TITLE
more NEWS Review Tasks

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#749]
Please assign yourself to the list of the products below (by tagging your name next to it) and review the NEWS.md file.
Mark as done if PR is merged or NEWS.md review has already been completed.

Couple things to note when updating NEWS.md:
* Make sure to only include information that's applicable from user's perspective.
* Check for typos or correction
* Collapse multiple entries to one when applicable
* Hide some non-user facing changes such as workflow updates, etc. 
* Use NEWS.md from dplyr/rlang/shiny repo as an example.

List of packages:
- [x] goshawk @donyunardi https://github.com/insightsengineering/goshawk/pull/175
- [x] osprey @mhallal1 https://github.com/insightsengineering/osprey/pull/101
- [X] teal.gallery @pawelru done
- [x] teal.connectors.cdse (internal only) @mhallal1 
- [x] teal.connectors.datasetdb (internal only) no change since last release
- [x] teal.connectors.rice (internal only) @mhallal1 
- [x] teal.connectors.snowflake (internal only) @mhallal1 no change since last release
- [x] teal.modules.hermes done
- [x] hermes.roche
- [x] helios.roche
- [x] helios
- [x] tern.rmbi https://github.com/insightsengineering/tern.rbmi/pull/42
- [x] mmrm
- [x] tern.mmrm
- [x] ggplot2.utils
- [x] nestcolor
- ~~formatters~~
- ~~rtables~~
- [X] chevron @pawelru https://github.com/insightsengineering/chevron/pull/286
- [X] citril @pawelru https://github.com/insightsengineering/citril/pull/114
- [X] citril.metadata @pawelru https://github.com/insightsengineering/citril.metadata/pull/49
- [X] dunlin @pawelru https://github.com/insightsengineering/dunlin/pull/32

**Comment by donyunardi** [comment]
I'm tasked to coordinate the NEWS.md update for all the packages that will be up-versioned for this release.

I see that @shajoezhu and I have opened several NEWS.md tickets already so this ticket is to cover the rest of the packages.

tagging @insightsengineering/statistical-engineering @insightsengineering/nest-sme teams for awareness and contribution. 

fyi @KlaudiaBB

**Comment by danielinteractive** [comment]
@donyunardi I just went through Stats Eng packages, I think only action left is for `teal.modules.hermes` probably good to let core team do that NEWS entry to be consistent across teal module packages re: reporter addition

**Comment by donyunardi** [comment]
thanks @danielinteractive!

**Comment by danielinteractive** [comment]
@nikolas-burkoff yeah we need to release the old version of `ggplot2.utils` because it is used in BAC.

**Comment by edelarua** [comment]
@nikolas-burkoff nothing to add for `nestcolor`. Everything looks fine there!

**Comment by Melkiades** [comment]
> So formatters and rtables are not our responsibility @Melkiades ?
I think the flow there is managed by @gmbecker. In `rtables`, I could not see grouping beside versions

**Comment by Melkiades** [comment]
tern.rbmi has only initialization entry in `NEWS.md`. I think this is closable @donyunardi

**Comment by donyunardi** [comment]
I only see one user facing commit which is around installation instruction in README.
Maybe we can add that in NEWS.md so we have some info when the package is upversioned to `0.1.1`?

**Comment by Melkiades** [comment]
The only change since the last release is minor readme rephrasing and contribution guidelines update. We could add these two entries

**Comment by donyunardi** [comment]
Sure, I'm okay with that. It will be more confusing to the user if we up-versioned without any context.

**Comment by Melkiades** [comment]
I created a PR to do that https://github.com/insightsengineering/tern.rbmi/pull/42

**Comment by donyunardi** [comment]
Thanks @Melkiades 

And that wraps it all! Thanks everyone!!
Closing ticket.
