### ISSUE TITLE
SRC showing sessionInfo() and other header information

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#752]
from @nikolas-burkoff 
- [x] SRC currently shows sessionInfo (or at least versions of NEST packages installed) - we are losing this. Should we be?
Edit: this might be fixed by https://github.com/insightsengineering/teal/pull/767

- [x] Also we are losing [this](https://github.com/insightsengineering/teal/blob/0f8f1e89fe49a6e33837437516ee2d53c89570c4/vignettes/teal-options.Rmd#L67) option  fixed by https://github.com/insightsengineering/teal/pull/774

- [x] We are also losing which library() calls we're using. Should we be? fixed by https://github.com/insightsengineering/teal/pull/774

**Comment by donyunardi** [comment]
It doesn't have to in show R code but should be somewhere.

**Comment by nikolas-burkoff** [comment]
Maybe look at putting it into teal rather than the modules would simplify things

**Comment by nikolas-burkoff** [comment]
I think for the sessionInfo we could have a hyperlink in the footer which if you click on opens a pop up with the session info

**Comment by Polkas** [comment]
We have three separate problems here and they are very important for the reproducibility objective (the core of the NEST).
I feel we should invest here some time and make sure we are happy with solutions.

- In my opinion already done part about session info could be improved with `sessioninfo::session_info()` or the renv lock file. Mostly nobody want to see the sessionInfo but to quickly reproduce the env so renv lock file could be the right direction.
@nikolas-burkoff what you think?
- So the "Show R Code" is not reproducible as no library calls are added by us now. This looks to be a part of teal.data and a feature of qenv.
- The teal code option is a part of qenv in teal.code for me. Not obvious have to achieve it.

Is it clear I have to go to sessionInfo to reproduce the env and then run the "Show R Code"? We should think about some Message in the "Show R Code" modal that 'please make sure the environment is properly reproduce with XYZ'.

**Comment by Polkas** [comment]
As we are not adding libraries on the level of qenv we do not know what packages are really needed.
As a result we persist the old behavior of adding all packages loaded in the R session (`sessionInfo`) https://github.com/insightsengineering/teal/blob/ffb0421e1ae7d5251e13dfb1bd2dd9dadd587924/R/get_rcode_utils.R#L41-L52 I think we should create a separate issue for investigating it as it was not implemented or discussed here

Another thing is that I proposed improvements to https://github.com/insightsengineering/teal/pull/767 which was not commented. @nikolas-burkoff 

A small thing is that we should rename the https://github.com/insightsengineering/teal/blob/ffb0421e1ae7d5251e13dfb1bd2dd9dadd587924/R/get_rcode_utils.R#L56 function as is misleading.

@mhallal1 @donyunardi I reopen the issue till we will discuss it.

**Comment by mhallal1** [comment]
> 1. As we are not adding libraries on the level of qenv, we do not know what packages are really needed.
>    As a result we persist the old behavior of adding blindly all packages loaded in the R session (`sessionInfo`) https://github.com/insightsengineering/teal/blob/ffb0421e1ae7d5251e13dfb1bd2dd9dadd587924/R/get_rcode_utils.R#L41-L52
>     I think we should create a separate issue for investigating it as it was not implemented or discussed here
> 2. Important to remember that when I will use qenv alone it still not have proper libraries. I expect that the end user (developer) should provide all needed library calls and is able to do that, then we do not need this step of adding blindly all dependencies. Each module could have a list of needed dependencies which are added at the beginning to the qenv.
> 3. Another thing is that I proposed improvements to [Add sessionInfo #767](https://github.com/insightsengineering/teal/pull/767) which was not commented. @nikolas-burkoff
> 4. A small thing is that we should rename the https://github.com/insightsengineering/teal/blob/ffb0421e1ae7d5251e13dfb1bd2dd9dadd587924/R/get_rcode_utils.R#L56
>     function as is misleading.
> 
> @mhallal1 @donyunardi I reopen the issue till we will discuss it.

@Polkas `qenv` is already merged on our main branch and we need to have the issues above covered asap for main users therefore we discussed and decided with @nikolas-burkoff to have those fixes for now, especially for the libraries. As this is an agile setup and the issue you suggest above is way more complex and requires a research issue by itself before implementation, please open a new issue with your points and the suggestions.

**Comment by Polkas** [comment]
I edit the issues and now I feel content with closing it.
Another issue
linked to https://github.com/insightsengineering/teal.code/issues/93
