### ISSUE TITLE
Replace `filters` argument in module and replace with `datanames` 

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#769]
Currently each module (teal_module class) has a field  [`filters`](https://github.com/insightsengineering/teal/blob/79678e78267098d1a0377f0b6b9cd8bba1cea988/R/modules.R#L289) which was used for a long time to indicate what datasets are used by the module so that filter-panel displays only module-relevant filter states.

Acceptance criteria:
- deprecate `filters` argument in `module` and recommend to use `datanames` instead.
- ~resolve `module$filter` in `teal::init` to include parent `datanames` also~ [done](https://github.com/insightsengineering/teal/blob/cf43277be1154ff0f3ef5e397118ab6051986e17/R/init.R#L148) 
- ~`resolve `module$filter` from `"all"` to all possible dataname`~ [done](https://github.com/insightsengineering/teal/blob/cf43277be1154ff0f3ef5e397118ab6051986e17/R/init.R#L148)
- `module$datanames` determines which datasets should be presented in filter-panel [see this](https://github.com/insightsengineering/teal/blob/cf43277be1154ff0f3ef5e397118ab6051986e17/R/module_tabs_with_filters.R#LL174C69-L174C85)  [see this](https://github.com/insightsengineering/teal.slice/blob/28ff2b274ba23ebb933ac4c98eea6df294d89c6d/R/FilteredData.R#L638)
- `module$datanames` determines which datasets are passed to the module [see this](https://github.com/insightsengineering/teal/blob/cf43277be1154ff0f3ef5e397118ab6051986e17/R/module_nested_tabs.R#L244)
- `module$datanames` should be `NULL` when `module$server` has no `data` argument. [see docs of the filters argument](https://github.com/insightsengineering/teal/blob/cf43277be1154ff0f3ef5e397118ab6051986e17/R/modules.R#L167)
- `module$datanames` when `NULL` filter-panel should be hidden. [logic here](https://github.com/insightsengineering/teal/blob/cf43277be1154ff0f3ef5e397118ab6051986e17/R/module_tabs_with_filters.R#L179)
- All apps in [teal.gallery](https://github.com/insightsengineering/teal.gallery) shouldn't have any failures

**Comment by donyunardi** [comment]
+1 to make module independent from filter feature and it does feel like a good idea to move `filters` argument from module to `init`.

> How to implement this in teal::init so that API will be easy to understand for the app developer.
Let's discuss this with @lcd2yyz to get info from user's perspective

Lastly I want to point out the obvious that we already have `filter` argument in `init` so we may want to think about a better argument name.

**Comment by lcd2yyz** [comment]
Thanks for the explanation. 
I agree it make more sense to rename argument to `datanames` within `teal::module`. It's a much better and self-explanatory description of what the argument intents to capture, so easier to understand for app developers. 
Now we just need to ensure a good deprecation strategy/message. Is it typical to do this with just one release cycle in-between?

**Comment by gogonzo** [comment]
Normally, deprecation takes one cycle, but it's up to us when we are going to remove `filters` from the `teal::module`. I think logic behind the change will be easy to communicate.

**Comment by chlebowa** [comment]
@gogonzo 

[This function](https://github.com/insightsengineering/teal/blob/720a374771b296460f0eee9dabf00d4891f7c831/R/module_nested_tabs.R#L293) makes no assertion on the `module` argument and that is utilized in unit tests to [pass a list](https://github.com/insightsengineering/teal/blob/main/tests/testthat/test-module_nested_tabs.R#L389C41-L389C41). Is there a valid reason behind this or is it just a dirty hack?

**Comment by gogonzo** [comment]
@chlebowa dirty hack in the test - probably didn't want to specify a module. Function should have an assertion
