### ISSUE TITLE
Precise library calls in the Show R Code for each module

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal#776]
Please refer to the comments by @Polkas in https://github.com/insightsengineering/teal/issues/752#issuecomment-1313285773

We should not add blindly all library calls for each SHow R Code call.
We have many options to add only needed dependencies, for each module.

linked to https://github.com/insightsengineering/teal.code/issues/93

**Comment by gogonzo** [comment]
Closing this in favour of previously existing. Moved comment to that issue https://github.com/insightsengineering/teal/issues/593
