### ISSUE TITLE
Create Acceptable Use Policy for assets generated by `teal` app

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#778]
### Summary
`teal` is a tool for exploratory usage so any assets (plots, tables, etc) generated by the `teal` app should not be use for regulatory need. `teal` user will need to be aware of this rule and agree to the Acceptable Use Policy before using the `teal` app.

### Intended Outcome
* Introduce the Acceptable Use Policy to the user when running `teal` app.
* A step where user has to agree to the policy before exploring data with teal.

### Execution:
* Decide how and where to introduce the Acceptable Use Policy in teal app
* https://github.com/insightsengineering/teal.widgets/issues/48
* https://github.com/insightsengineering/teal/issues/812

**Comment by pawelru** [comment]
`teal` is aimed to be a company agnostic tool for visualising data and this policy seems to be a very Roche specific requirement. Therefore I don't quite agree with the scope of this task.

**Comment by pawelru** [comment]
Yes, I saw changes in watermark and I am pleased that it got removed. That was a good decision.
My current concerns are around non-clinical data analysis. I am thinking now about biomarker exploratory data analysis via `teal.modules.hermes`. During our last F2F even we had a quick session showing off database exploration. This all makes me think that teal might be used outside of clinical data world and this change request (at the most general level of `teal` itself) somewhat locks the scope. Not all the target audience would be interested in it.
Moreover I am also thinking whether this requirement is on the higher level - i.e. (and should be addressed) on the _environment_ level - in particular not on the _tool_ level. In terms of Roche terminology - users of OCEAN analytical environment had to acknowledge the disclaimer what's allowed and what's not. I don't think that each of the tool enabled/installed there has to have this type of disclaimer. That would be bad design decision to me to delegate that responsibility down.

Your implementation ideas are good but I am still not 100% convinced that we should do this at all.

**Comment by lcd2yyz** [comment]
I agree to both of your points - `teal` may/can be used outside clinical world, and the enforcement of proper usage should be done at higher level (communication and trainings etc)

But to you specific example about using `teal.modules.hermes` for biomarker exploration - who is to stop a research scientist (who received a link to the app from another colleague, so may not have heard about the usage policy) to play around with the app and found some cool-looking signals, then decided to download the table/plot and use it in a conference presentation material. The disclaimer mechanism can be a way of reinforcement training to educate the users about proper usage.

There are analogous examples in our everyday-settings - companies like Starbucks and McDonalds print warning labels like "Caution: Content hot" on coffee cups.

This new option should not impact on the current code structure, and should not result in backward-compatibility issues. The default can be set to "disabled". Then specifically for Roche users, we would update NOAH to communicate that the disclaimer needs to be enabled for all apps that use clinical trial data. Again, this disclaimer mechanism can in fact be used for any purpose, not necessarily to the problem of clinical data usage, but any attempt to limit the liability of the app developers inside or outside of pharma.

**Comment by pawelru** [comment]
Looking at this requirement once again after a short break I still see it as an _application_ requirement - not necessarily a _tool_ requirement. The definition is that there is only one (actually a few but let's stick to just one) _tool_ (i.e. `teal` R package) which can be used in many ways to create multiple various _applications_ (i.e. shiny apps). My goal is to make a _tool_ as open and extendible as possible whereas _application_ needs to implement specific business logic and requirements. I am concerned that we are about to address some business requirement on the level of _tool_ which might not be suitable for some of the _applications_. 

Continuing example of a cup: a straw is not an integral part of a cup itself. A cup has a dedicated place to put any kind of straw you like or you are free to decide not to use one at all. IMO we are trying to build a cup with a specific type/shape/colour of straw.

Coming back to `teal`. I have few ideas:
- home page module inside tmg - this however might be unavailable if one is relaying on tmc or tmh only
- enhance examples inside `teal.gallery` to have this implemented in its home page / footer / wherever else. 
    ```
    teal::init(
      data = ...,
      modules = list(
        module(
          "home",
          server = function(input, output, session, data) {
            observe({
              showModal(modalDialog(
                title = "Acknowledge me!",
                "This is an acknowledge message"
              ))
            })
          },
          ui = ...
        ),
        ...
      )
    )
    ```
    I believe that the apps stored there is widely used as a base for a new app development. We can also add that in the NOAH instructions.

**Comment by lcd2yyz** [comment]
Coming back to this after some time with a fresh mind, I can understand your perspective on differentiating between application vs tool. Your suggestion of moving this to module-level implementation does make sense. 

> * home page module inside tmg - this however might be unavailable if one is relaying on tmc or tmh only

I like this approach better (than embedding example code within `teal.gallery`). We already have things like `tm_front_page`, `tm_file_viewer` available in tmg, that are not necessarily analysis-based, but more functional based, in-line with this pop-up requirement.

Do you have a strong opinion about implementing it as a new separate module, something like `tm_popup`, or as some additional option/argument to the existing `tm_front_page` itself?

**Comment by donyunardi** [comment]
Completed.
