### ISSUE TITLE
Use tdata inside teal::init

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal#783]
Should be done with https://github.com/insightsengineering/teal.data/issues/121

Once the output of TealData$pull is a `tdata` object then `teal::init` should be updated to reflect this change

**Comment by gogonzo** [comment]
I'd suggest to make changes in when `cdisc_data` is called - if all datasets are available (no DDL), then cdisc_data should return `tdata` with all necessary informations, such as:
- JoinKeys
- Probably we need to store CodeClass in code attribute as we need a way to subset code for selected datasets. `code` could be an expression only if we decide to not subset the code or if we figure out [this](https://github.com/insightsengineering/teal.data/issues/37)

**Comment by donyunardi** [comment]
### Acceptance Criteria:
* `tdata` object should be used in `teal::init` in the body (not as an argument)
* `tdata` will be consume by filter panel and modules (tdata already used in modules)
* `tdata` initialize sooner 

Merging this will need to be done with #121

**Comment by asbates** [comment]
I'm looking at working on this issue but I don't understand it.

- I don't see a `pull` method for `TealData`. Is this referring to the connection classes? If so they return self so I don't see how this works.
- What is meant by the 'output'? Is that the `TealData$get_tdata` method being added with insightsengineering/teal.data/pull/138?
- I don't see where the `t_data` transformation should happen in `teal::init`.

**Comment by gogonzo** [comment]
Closing - irrelevant anymore
