### ISSUE TITLE
Assess the known bugs note on setting `options(shiny.useragg = FALSE)` for teal with shiny 1.7.4 update

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#794]
### Summary
We communicated to users to set `options(shiny.useragg = FALSE)` when running teal app due to issue with `ragg`.
https://github.com/insightsengineering/teal/blob/c08a80ef9b3d81b51a1debbc483bda14460b70bc/vignettes/teal.Rmd#L117

@Polkas submitted an issue to shiny and it was addressed with latest shiny update:
https://github.com/rstudio/shiny/blob/5eb442aa03c09e759398b76b1124e4c50b9695cc/NEWS.md?plain=1#L12

All related issues are:
* https://github.com/insightsengineering/teal.modules.general/issues/438
* https://github.com/rstudio/shiny/issues/3704
* https://github.com/rstudio/shiny/issues/3735

It seems that the issue has been addressed from shiny end by adding some protection on NULL values. 
This means, we may not need to set `options(shiny.useragg = FALSE)`.

### Acceptance Criteria
* using shiny 1.7.4, test the exploratory app that was done in insightsengineering/teal.modules.general/issues/438
* If the bug no longer occur, update the "known-bugs" documentation to set `options(shiny.useragg = FALSE)` for `shiny < 1.7.4`

**Comment by pawelru** [comment]
done
