### ISSUE TITLE
[BUG]: teal apps are slow and vulnerable to the change in the data

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal#803]
If you run any app containing n-modules (eg. `exploratory`) please do following:
1. Turn on logs `options(teal.log_level = "TRACE", teal.show_js_log = TRUE)`
2. Run the app
3. Add and change any filter value and see what happens in the logs - you can see logs being called from many modules.

We have following problem:
- All modules which have observe or observeEvent they trigger calculation of the reactives to get needed values. Normally it's not a problem with the outputs, which trigger re-calculation of the reactives when they are visible. For example renderPlot in any module triggers only when we change the tab.
- We were vulnerable to this problem for years and solution might be very simple - to guard reactives passed to the modules by `teal` with simple `eventReactive` based on the change of the tabs.

**Comment by donyunardi** [comment]
### Acceptance Criteria:
* Prevent the computation of the data in inactive module
* Trigger reactive when the tab is changed

**Comment by nikolas-burkoff** [comment]
Example app:
```
library(teal)

my_module <- function(label = "Example", time_delay = 3) {
  module(
    label = label,
    server = function(id, data) {
      moduleServer(id, function(input, output, session) {
        observeEvent(data(), {
          print(sprintf("Trigger for module %s with time delay %f", label, time_delay))
          Sys.sleep(time_delay)
          print(sprintf("Trigger for module %s with time delay %f completed", label, time_delay))
        })
      })
    }
  )
}

app <- init(
  data = teal_data(dataset("iris", iris)),
  modules = list(
    my_module("Short delay", 0.5),
    my_module("Long delay", 5)
  )
)

runApp(app)

```

Note on app load (and changes to data in the filter panel) we see the trigger in both modules being shown - not just the active module.

![image](https://user-images.githubusercontent.com/15201933/216559226-2f88985e-0cce-45fb-9cef-6e355d1d1964.png)
