### ISSUE TITLE
[Feature Request]: Enable a mechanism to display message that require app user action

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal#812]
Discuss implementation detail of https://github.com/insightsengineering/teal/issues/778

### Summary
Implement a mechanism to allow app developer to enable an option to display a customizable message (eg. acceptable use policy, caution/warning, etc) that need to be consciously dismissed/accepted/closed by the end user via an action button.

### Ideal behavior
At backend - for app developer
- Enable the mechanism to turn on/off the functionality in app code
- Able to customize the message to be displayed
- Able to customize the label of the action button

At app front - for app users
- Upon opening the app, a dialog window pops-up showing the customized message.
- Has to click on the action button to dismiss/accept the message, in order to close the pop-up, before continuing to interaction with the shiny app.

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Propose a design solution to support this feature
* Identify products affected (i.e. will it impact all modules?)

**Comment by m7pr** [comment]
Hey @donyunardi @lcd2yyz , below you can see my initial proposition.

The name: `Consensus Panel`  /  `Consent Panel`
The affected products: `teal::init` will be extended with `consensus`  /  `consent` parameter, which is set to NULL by default and does not affect the current behavior when it's NULL. This ensures backward compatibility.

`consensus`  /  `consent` parameter takes an object of class `consensus_panel` / `consent_panel` that can be created with a function `consensus_panel()` / `consent_panel()` that takes

```{R}
consensus_panel <- function(
    title = NULL, # not visible if null, not required
    statement = NULL, # required
    agree_text = NULL, # required
    disagree_text = NULL # not visible if null, not required
    ) {

}
```

and each parameter represent the text on a Consensus Screen

<img width="494" alt="consensus" src="https://github.com/insightsengineering/teal/assets/133694481/0c47717a-af51-4c04-bcf4-394ebe14e302">

If the `disagree_text = NULL` then we do not have the disagree button visible. A click on the agree button moves you to the app, and if there is a disagree button and someone disagrees then the app is closed.


The feature would require a creation and documentation of `consensus_panel()` / `consent_panel()`  function and the extension of `teal::init()` function, which can be tackled in one issue [this issue].

Any objections or further suggestions?

**Comment by chlebowa** [comment]
I assume clicking `agree` would be necessary to enable viewing of or interaction with the app.
Would this appear in a popup that covers/disables the app?

Required arguments should not have default values.

**Comment by m7pr** [comment]
> I assume clicking agree would be necessary to enable viewing of or interaction with the app.
Would this appear in a popup that covers/disables the app?

Yes this is my vision as well.

> Required arguments should not have default values.

Correct

**Comment by m7pr** [comment]
Hi @lcd2yyz , just flagging this one. I saw your discussion with @pawelru in https://github.com/insightsengineering/teal/issues/778 about potential solutions that we can reuse from our arsenal. Did you guys finally agreed if it's ok to create a new, small module in tmg (based on `showModal(modalDialog`), or we rather use `tm_front_page` for that?

**Comment by lcd2yyz** [comment]
@m7pr Apologies for the late reply, last week had been quite hectic for me, so I forgot to reply on your proposal.

> Did you guys finally agreed if it's ok to create a new, small module in tmg (based on `showModal(modalDialog`), or we rather use `tm_front_page` for that?

No, we didn't settle on a final execution, where #778 ended is exactly where our conversation ended :joy:

I would prefer a separate module altogether, as this will allow app developers to implement the popup disclaimer, without adding a "permanent" page/tab to the app itself. But I'm not objecting to add to `tm_front_page` either, if there are other technical consideration/limitations.

Your design generally looks great to me, both the UI and API. 

But I'm having some doubt about the disagreeing button. It's something I never thought about previously (so was not part of the original requirement), so thanks for suggesting it! But since `disagree_text` is designed to be optional, what should be the meaning of "disagreeing"?
- Should app closing be the only option? And even if so, maybe there should be another message to say "You won't be able to access the app without giving consent, therefore the app will be automatically closing in 5...4...3...2...1 sec" to avoid closing the app being too abrupt? 
- Should we allow other extensible actions upon "disagreeing", for example, being re-directed to another app/page. Since the API allows a customizable text for disagree button, one could actually specify something like `disagree_text = 'I don't want to be responsible for accessing restricted date, let me use dummy data instead'`

I don't have a clear answer in my head either, so "talking out loud" here. Do you have more clear and formulated thoughts on it?

**Comment by m7pr** [comment]
Thanks for the answer @lcd2yyz . I personally prefer a new short module than the extension of `tm_front_page` as the latter is a permanent part of the app. `tm_front_page` can be used now, temporarily, until we come up with a clear idea on the welcome popup. 

I would stick with your original idea, where there is only a headline, message and `approve/acknowledge` button that closes the popup. The only extension I'd suggest is an ability to add one more (non-mandatory) button, that can have any text and can have the `action` ability that gets triggered the moment you click on this second button. The actions we could consider are limitless - app developer provides his/her own custom action, e.g. closing of the app, a redirect to another url, some action with a deletion of the data.

Do you think that make sense for the first stab? If yes, I can proceed with an implementation and once I'm done we will review it together.

**Comment by lcd2yyz** [comment]
@m7pr sounds great! Looks like we also have consensus to create a new module as well. Some naming suggestions `tm_popup_disclaimer` or `tm_landing_popup`? Looking forward to seeing the first version!
