### ISSUE TITLE
[Bug]: Docs link to missing rdrr.io pages

### ISSUE THREAD

**Issue by slodge** [insightsengineering/teal#813]
### What happened?

Several links on the documentation on https://insightsengineering.github.io/teal/latest-tag/articles/teal.html seem to point to 404 rdrr.io targets - e.g. to https://rdrr.io/pkg/teal.data/man/teal_data.html

I guess this might just be because teal isn't yet fully released - in which case, please feel free to mark this as "won't fix" until that happens (y)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Hi @slodge
Can you point out specifically where you find this missing link?
I am looking at the vignette code and I don't see any link that's pointing to rdrr.io.

**Comment by slodge** [comment]
I think it's in the links the code this snippet generates -
https://github.com/insightsengineering/teal/blob/e8a67d1f623c16b101b70ddd39caae2426d6d2e3/vignettes/teal.Rmd#L40

If this will just fix after cran release then please do ignore it.

(Sorry this is brief - I'm really 10 minutes from takeoff...)

**Comment by slodge** [comment]
I think there's something in "across packages" on
https://cran.r-project.org/web/packages/pkgdown/vignettes/linking.html that
can help - but definitely can't test it right now.

Thanks for looking. Sorry for flying off!

**Comment by donyunardi** [comment]
Got it, thanks for pointing this out!
We'll look into this.

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Fix broken links in the vignette's code example

**Comment by pawelru** [comment]
I don't think that there is much we can do. This is how `pkgdown` works.

> If pkgdown can find a pkgdown site for the remote package, it will link to it; otherwise, it will link to https://rdrr.io/ for documentation and CRAN for vignettes.

[source](https://pkgdown.r-lib.org/articles/linking.html#across-packages)

The bottom line is that we will wait until `teal` will hit the CRAN which is rather sooner than later.

**Comment by donyunardi** [comment]
Agree, let's wait until teal hit CRAN and we'll close this issue.

**Comment by pawelru** [comment]
@donyunardi shall we close this guy then?

**Comment by donyunardi** [comment]
We can, yes.
If issue still persists after we post to CRAN, we can reopen.
