### ISSUE TITLE
[Question]: Why character, not expression?

### ISSUE THREAD

**Issue by iqis** [insightsengineering/teal#814]
### What is your question?

from https://insightsengineering.github.io/teal/latest-tag/articles/including-adam-data-in-teal.html, why does `code` argument in `cdisc_dataset()` take its point in character (which you'd have to escape), instead of an expression? 

```r
adsl <- synthetic_cdisc_data("latest")$adsl
adtte <- synthetic_cdisc_data("latest")$adtte

cdisc_data_obj <- cdisc_data(
  cdisc_dataset(dataname = "ADSL", x = adsl, code = "ADSL <- synthetic_cdisc_data(\"latest\")$adsl"),
  cdisc_dataset(dataname = "ADTTE", x = adtte, code = "ADTTE <- synthetic_cdisc_data(\"latest\")$adtte")
)
class(cdisc_data_obj)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
Thanks for your question. It might be a little confusing at the very beginning but it was done for some reason. At the moment of developing that functionality, one of the key requirements was to keep code comments to increase readability of ShowRCode output. This is not possible to achieve with expressions.

```
> expression({
+     # foo
+     x <- 2
+ })
expression({
    x <- 2
})
> rlang::expr({
+     # foo
+     x <- 2
+ })
{
    x <- 2
}
```
