### ISSUE TITLE
Review `teal` documentation before release

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#815]
### Summary
Related with insightsengineering/nestdevs-tasks#13
In preparation to release `teal`, we need to review/assess all documentation in the package. 

### Acceptance Criteria
* Review roxygen examples on all functions
  * Test examples
  * If it's using chunk, update to `qenv`.
* * Review vignettes on these topics only:
  * Review any content around `qenv`
  * Review any content around `chunks` (i.e. make sure the right language around deprecation)
  * Review any content around shinyvalidate
* Update NEWS
* Update README (if applicable)
* Review DESCRIPTION file (i.e. dependency versions, etc)

**Comment by asbates** [comment]
I'm going to make a running list of notes here.

- There are reference to chunks in `R/get_rcode.R` and it's associated test file. The functions here have chunks deprecation warnings.

**Comment by asbates** [comment]
`?example_module` example app errors when adding a filter.

code:

```
 devtools::load_all("teal")

 app <- init(
   data = teal_data(
     dataset("IRIS", iris),
     dataset("MTCARS", mtcars)
   ),
   modules = example_module()
 )
   shinyApp(app$ui, app$server)
```

Add a filter for `Sepal.Width` in `iris`.

**Comment by nikolas-burkoff** [comment]
Checking you are on the filter refactor branch of teal and teal.slice (as I assume that's what will be released)

**Comment by donyunardi** [comment]
I was able to reproduce this.
In addition, you cannot remove the filter state from the right-hand side panel directly. The only way to remove it is by clicking the 'x' button on the left-hand app, but this will only remove one of the two copies of the filter state.

**Comment by donyunardi** [comment]
> `?example_module` example app errors when adding a filter. I think this may be limited to numeric filters, specifically rendering the histogram above the slider.
> 
> code:
> 
> ```
>  devtools::load_all("teal")
> 
>  app <- init(
>    data = teal_data(
>      dataset("IRIS", iris),
>      dataset("MTCARS", mtcars)
>    ),
>    modules = example_module()
>  )
>    shinyApp(app$ui, app$server)
> ```
> 
> Add a filter for `Sepal.Width` in `iris`.

I was able to run it the example just fine:

![image](https://user-images.githubusercontent.com/8597300/228719933-d8667b82-cd4a-439d-9899-923792cd1fd6.png)

Any chance you were not using the main branch version of `teal.slice`?

**Comment by asbates** [comment]
> Any chance you were not using the main branch version of `teal.slice`?

Just double checked. I'm on main for both teal and teal slice. And used devtools::load_all() for both packages to ensure the correct branch. Still getting the error.

**Comment by donyunardi** [comment]
@chlebowa @nikolas-burkoff @BLAZEWIM any chance you guys can try this?

**Comment by nikolas-burkoff** [comment]
It seems to work ok for me:
![image](https://user-images.githubusercontent.com/15201933/229056604-eb64836f-257a-4742-ad44-f875b2b13608.png)

I wonder if there's a difference in an external dependency?

**Comment by BLAZEWIM** [comment]
Confirm, works for me
![image](https://user-images.githubusercontent.com/110387997/229060326-c333041c-d8b8-4eac-adcf-8bc079b53a97.png)

**Comment by chlebowa** [comment]
Only works for me if I `load_all` `teal.slice`. When `teal.slice` is attached with `library` I get this:
```
Listening on http://127.0.0.1:3399
Warning: Error in ..stacktraceon..: data all is not available
  3: runApp
  2: print.shiny.appobj
  1: <Anonymous>
```

`teal` is installed from refactor branch and attached with `library`.

**Comment by asbates** [comment]
Regarding the errors with the range slider plot, I think this is an [ggplot2/rlang issue](https://github.com/tidyverse/ggplot2/issues/5235). I had ggplot2 3.4.1 which correctly requires rlang >= 1.1.0. However for some reason I still had rlang 1.0.6 installed.

I'll go back through the examples and update the bullets above.

**Comment by donyunardi** [comment]
> Only works for me if I `load_all` `teal.slice`. When `teal.slice` is attached with `library` I get this:
> 
> ```
> Listening on http://127.0.0.1:3399
> Warning: Error in ..stacktraceon..: data all is not available
>   3: runApp
>   2: print.shiny.appobj
>   1: <Anonymous>
> ```
> 
> `teal` is installed from refactor branch and attached with `library`.

We're focusing on `main` branch for now.
