### ISSUE TITLE
Update docs for filter panel refactor

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal#816]
The docs for `teal::init` show how to specify filter settings with a nested list structure. When insightsengineering/teal.slice/pull/222 is complete, these docs will need to be updated.

**Comment by chlebowa** [comment]
Handling of `teal_slice` objects has already been introduced on `teal` branch `187_new_api@filter_panel_refactor@main`, so we can proceed amending docs there. I suggest using `?teal.slice::teal_slice` as template/inspiration/source.

**Comment by gogonzo** [comment]
vignette and documentation updated
