### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal#818]
There are a couple of issues (some potential) noted in the review of documentation in #815. I think they need more discussion, hence this issue.

- The vignette "Adding support for Reporting to custom modules" uses `qenv` in an example. I think we should add a short description of qenv, point to `teal.code`, or remove the `qenv` usage possible.
- ~~The examples in `module_tabs_with_filters` uses `:::`. These shouldn't be used.~~
- I don't understand the purpose of the second example in `module_tabs_with_filters`. If it doesn't add anything helpful it should be removed. Similar examples are used in other teal functions so they may need updating as well
- ~~Similarly for `module_teal`. It uses `:::` and I'm not sure the example is helpful.~~

**Comment by m7pr** [comment]
blocked by #870
