### ISSUE TITLE
Fix validation message

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#821]
> Good findings.
> 
> Also, we should improve the validation message given out here:
> 
> ![image](https://user-images.githubusercontent.com/8597300/229927375-eb6eb555-3da8-4040-ac6e-2c1965d3cd99.png)
> 
> The current message implies that all columns do not exist where it supposed to be just for `TRT` column.

_Originally posted by @donyunardi in https://github.com/insightsengineering/teal/pull/819#discussion_r1157792052_

### Acceptance Criteria
* Validation message should only show the missing columns, not all columns selected in the shiny input.            
* Using the example above, the validation should say `ADSL does not have the required variables: TRT`

**Comment by asbates** [comment]
FYI this is for `validate_has_variable`.

**Comment by chlebowa** [comment]
Fixed [here](https://github.com/insightsengineering/teal/pull/877)
