### ISSUE TITLE
R CMD Check NOTE - Possible dependencies to remove

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal#826]
> The 1 NOTE for teal is:
> ```
> * checking dependencies in R code ... NOTE
> Namespaces in Imports field not imported from:
>   ‘lifecycle’ ‘styler’ ‘teal.code’
>   All declared Imports should be used.
> ```

_Originally posted by @cicdguy in https://github.com/insightsengineering/idr-tasks/issues/531#issuecomment-1516446682_

### Summary
We got some note from R CMD Check to address around three packages: lifecycle, styler, and teal.code
* We use lifecycle for the badges in roxygen note so we can't remove this
* styler is being used in pre-commit yaml file, maybe that's why this is in DESC?
* There are some references of `teal.code` in vignettes. If we remove the teal.code from DESC, we will see another NOTE:
```r
❯ checking for unstated dependencies in vignettes ... NOTE
  '::' or ':::' import not declared from: ‘teal.code’
```

### Acceptance Criteria:
* TBD

**Comment by donyunardi** [comment]
Based on this, maybe we can move lifecycle to Suggest:
https://lifecycle.r-lib.org/reference/badge.html

> lifecycle::badge() is run by roxygen at build time so you don't need to add lifecycle to Imports: just to use the badges. However, it's still good practice to add to Suggests: so that it will be available to package developers.

**Comment by donyunardi** [comment]
Tried to move lifecycle to Suggest and got this note:
```r
── R CMD check results ───────────────────────────────────────────────────────────────────────────────────────────── teal 0.12.0.9026 ────
Duration: 5.2s

❯ checking package dependencies ... ERROR
  RdMacros package not required: ‘lifecycle’
  RdMacros packages must be contained in the DESCRIPTION Imports/Depends
  entries.
  
  See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
  manual.
```

Not sure why we need `RdMacros` in DESCRIPTION file.

**Comment by pawelru** [comment]
> Not sure why we need `RdMacros` in DESCRIPTION file.

It was needed to enable rendering lifecycle badges in the roxygen documentation. I am not 100% sure whether it is still needed. Please have a look at `usethis::use_lifecycle`. Under version [`1.6.3`](https://github.com/r-lib/usethis/blob/v1.6.3/R/lifecycle.R#L25) it's adding `RdMacros` entry whereas starting from [`2.0.0`](https://github.com/r-lib/usethis/blob/v2.0.0/R/lifecycle.R) it's not. Worth re-checking this and apply corrections to all repos.

**Comment by m7pr** [comment]
This does not appear in GHA builds anymore: 
https://github.com/insightsengineering/teal/actions/runs/5622540254/job/15235387457#step:21:123

**Comment by m7pr** [comment]
I think the incident was closed when you posted it, but my comment meant that GHA actions no longer throw this NOTE during R CMD CHECK build when they work
