### ISSUE TITLE
[Feature Request]: Enable Teal framework work with datasets generated in the Shiny app 

### ISSUE THREAD

**Issue by cibo-feng** [insightsengineering/teal#856]
### Feature description

Some R Shiny apps will take user inputs to do simulations or other calculations to generate datasets. It will be great if Teal framework could work on these datasets additional to the source datasets (which exist before the Shiny-running and can be handled by Teal). Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
@donyunardi @lcd2yyz This seems to be completed with `teal_data_module`. https://insightsengineering.github.io/teal/main/articles/data-as-shiny-module.html

**Comment by donyunardi** [comment]
I agree!

@cibo-feng 
Can you please review the vignette to determine if this new feature could assist you in resolving the issue?

**Comment by lcd2yyz** [comment]
Hi @cibo-feng

Would you be able to help clarify which workflow is your use-case scenario?
1) Original dataset -> perform simulation or other calculations based on the original dataset -> [pass into teal app] filtering data via teal app -> summary/visualization with teal modules
2) Original dataset -> [pass into teal app] filter data via teal app -> perform simulation or other calculations based on the filtered datasets -> summary/visualization with teal modules.

If it's use-case 1 - this should be already available via the new `teal_data_module` as pointed out above with `teal >=0.15.0`, for which we will close the issue. However, if it's use-case 2 - we will need to refine the issue further.

**Comment by cibo-feng** [comment]
Hi @lcd2yyz, @donyunardi and @gogonzo, 

I missed your messages from the last December. Sorry a lot. 

The work flow in my case is as below:
No dataset -> perform simulations based on user inputs -> filter data and/or summary&visualization

I guess your use-case 1 can cover this?

Thank you.

**Comment by lcd2yyz** [comment]
Yes @cibo-feng! Please give `teal >=0.15.0` a try, the new `teal_dat_module` feature should support your use case now.

**Comment by cibo-feng** [comment]
Thank you @lcd2yyz !
