### ISSUE TITLE
[Feature Request]: Differentiating "not applied" and "not applicable" in filter manager matrix

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal#866]
### Feature description

Consider the following code

```
default_filters <- teal::teal_slices(
  teal_slice("iris", "Sepal.Length", sel = c(5.5, 6.5), fixed = FALSE),
  teal_slice("iris", "Species", anchored = TRUE),
  teal_slice("mtcars", "mpg"),
  module_specific = TRUE,
  mapping = list(
    table = c("iris Sepal.Length"),
    funny = c("iris Species"),
    global_filters = "mtcars mpg"
  )
)

app <- init(
  data = teal_data(
    dataset("iris", iris),
    dataset("mtcars", mtcars)
  ),
  modules = modules(
    tm_data_table(
      "table",
      variables_selected = list(),
      dt_args = list()
    ),
    funny_module("funny", datanames = "iris"),
    funny_module("funny2", datanames = "mtcars")
  ),
  filter = default_filters
)
```

- `mtcars` dataset is not used in `funny` module 
- `iris` dataset is not used in `funny2` module
![image](https://github.com/insightsengineering/teal/assets/78242757/ed1c6f77-d558-4b1c-bc42-ec3a6165f49a)

Filters should be considered "not applicable" if the module is not using the dataset that the filter variable is from. Thus instead of showing X mark, should display an icon that would convey meaning of "NA", for example https://www.compart.com/en/unicode/U+2796

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
[duplicate](https://github.com/insightsengineering/teal.slice/issues/376)
