### ISSUE TITLE
[Feature Request]: UX improvements on snapshot/filter manager

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal#883]
### Feature description

Improve user experience by:

* Placing descriptive text instead of displaying an empty modal window with icons
  * (see mockup 1 below)
* Press enter to submit 

#### Mockup 1

![image](https://github.com/insightsengineering/teal/assets/211358/82db31e5-69b3-4eef-b9ec-213aa7cdb9b6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by lcd2yyz** [comment]
Image is broken, can you attached the mockup again?

**Comment by averissimo** [comment]
Done, it should appear to everyone now
