### ISSUE TITLE
blueprint vignette fails to render

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#940]
When rendering the blueprint `qenv` vignette  I get this error:

```
pandoc: /tmp/RtmpFbIXam/preview-2a2a2cfb3b5d.dir/qenv_files/figure-html/qenv_dot_diagram-1.png: withBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1
In addition: Warning message:
In file.rename(f1, f2) :
  cannot rename file 'dot2af0ded89af.png' to '/tmp/RtmpFbIXam/preview-2a2a2cfb3b5d.dir/qenv_files/figure-html/qenv_dot_diagram-1.png', reason 'Invalid cross-device link'
Execution halted
```

This also prevents me from running R CMD CHECK on `teal` locally.

**Comment by donyunardi** [comment]
Just want to mention, I had to `brew install graphviz` on my local machine when I worked with the PR, which is why I made this comment:
https://github.com/insightsengineering/teal/pull/923#discussion_r1340563756

Do you have `graphviz` locally by any chance?

**Comment by chlebowa** [comment]
That error is after installing `graphviz`, before it was a different one.
