### ISSUE TITLE
printing `teal_module(s)` objects

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#942]
Printing `teal_module` and `teal_modules` is implemented by `print` calling `cat(toString(x))`. This is unusual, typically it would be done with `cat(format(x))`. Perhaps we should change it.

**Comment by m7pr** [comment]
@chlebowa would it be sufficient to globally replace `toString` with `format`?

**Comment by chlebowa** [comment]
There might be more to it but a quick glance at the `toString` methods makes me thin much of the work is done.
