### ISSUE TITLE
[Bug]: Old teal logo on github.io 

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal#949]
### What happened?

Not sure why our teal website (https://insightsengineering.github.io/teal/latest-tag/) still showing the old logo.
Also the NEST logo on the top-left does not link to the new NEST website (the Pharmaverse logo beside it does)

![image](https://github.com/insightsengineering/teal/assets/78242757/f48e7ff4-8ac8-422e-a37e-a641c67148cb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by lcd2yyz** [comment]
And the icon at the bottom of the page is also broken
![image](https://github.com/insightsengineering/teal/assets/78242757/1979bd34-1cd8-4481-ad63-d0fe591a3428)

**Comment by lcd2yyz** [comment]
And our IE GH main page also reverted to old logos 🤔 
![image](https://github.com/insightsengineering/teal/assets/78242757/b774e99b-73d9-4958-a6a0-150534f40421)

**Comment by donyunardi** [comment]
> And our IE GH main page also reverted to old logos

The logos are being pulled from `thumbs` folder and I updated the `thumbs` folder with this PR:
https://github.com/insightsengineering/hex-stickers/pull/33

It display the new logos but looks a bit stretched:
<img src="https://github.com/insightsengineering/teal/assets/8597300/b2a24f1f-971b-4c9b-9c3f-9d5f7b934807" width="50%" height="50%" />

I'll fix this.

> Not sure why our teal website (https://insightsengineering.github.io/teal/latest-tag/) still showing the old logo

We updated the logo in the main branch, but a new release hasn't been made yet. As a result, the latest tag still points to the old logo. This will be resolved once we make a new release.

<img src="https://github.com/insightsengineering/teal/assets/8597300/72a0847a-3eab-4d30-8f67-d4ff696df27a" width="50%" height="50%" />

> And the icon at the bottom of the page is also broken

We need to remove the `s` in `https` link to repo roster. This applies to all teal repos (including modules).
@cicdguy any magic button to push all this update at the same time or is this something that I need to do manually?

**Comment by donyunardi** [comment]
Actually, I did fix the logo a while back in `github.com/insightsengineering/.github` repo on [this commit](https://github.com/insightsengineering/.github/commit/0b7a6691332e10179ce5b343d058c05e61fcd0f1) and I can see the logo looks good:

<img src="https://github.com/insightsengineering/teal/assets/8597300/db9c571c-3700-4f24-82d7-3b2fbbfd9019" width="70%" height="70%" />

However, the current `github.com/insightsengineering` is pointing to `.github-private`. 

I don't know what's the difference between `.github` and `.github-private`.
@cicdguy can you please help shed a light on this?
Should I bring over the changes that I did in `.github` to `.github-private`?

**Comment by donyunardi** [comment]
Got it, thanks!

Any thoughts about this one?

> We need to remove the s in https link to repo roster. This applies to all teal repos (including modules).
@cicdguy any magic button to push all this update at the same time or is this something that I need to do manually?

**Comment by donyunardi** [comment]
Copy that.
I'll make the update.

**Comment by donyunardi** [comment]
Logo display is fixed in `.github-private` [here](https://github.com/insightsengineering/.github-private/pull/15#pullrequestreview-1744931243). Thanks @averissimo !

**Comment by donyunardi** [comment]
All issues are addressed. 
Closing.
