### ISSUE TITLE
[Bug]: <teal_data() does not accept data.frame as it does by vignette>

### ISSUE THREAD

**Issue by Dannyzhd** [insightsengineering/teal#959]
### What happened?

Dear development team, I tried the following example code from the vignette: [Using General Data in teal Applications]([url](https://insightsengineering.github.io/teal/main/articles/including-general-data-in-teal.html)) 

library(teal)

app <- init(
  data = teal_data(
    IRIS = iris, CARS = mtcars,
    code = "IRIS <- iris
            CARS <- mtcars"
  ),
  modules = example_module()
)

if (interactive()) {
  shinyApp(app$ui, app$server)
}

on my laptop with
Rstudio 4.3.1
teal 0.14.0
teal.data 0.3.0

### sessionInfo()

```R
Error in teal_data(IRIS = iris, CARS = mtcars, code = "IRIS <- iris\n            CARS <- mtcars") : 
  Assertion on 'data_objects' failed: May only contain the following types: {TealDataset,TealDatasetConnector,TealDataConnector}, but element 1 has type 'data.frame'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Hi @Dannyzhd 

I believe you're referring to [this](https://insightsengineering.github.io/teal/main/articles/including-general-data-in-teal.html) vignette. If so, then you are looking at the development version of vignette, which only only works with the development version of teal.

The code that you provided is using our development version of `teal` and `teal.data`.

If you're using the stable version, then you can explore our `latest-tag` vignette, starting from [here](https://insightsengineering.github.io/teal/latest-tag/).

**Comment by donyunardi** [comment]
Closing for now but feel free to reach out for more question.

**Comment by Dannyzhd** [comment]
Hi @donyunardi thanks soo much for the swift response!

Basically I am trying to learn teal and its sub-packages, all on the stable version. So from the latest-tag  [latest-tag vignette](https://insightsengineering.github.io/teal/latest-tag/) you linked above,
I navigated to[ the vignette for teal.data](https://insightsengineering.github.io/teal.data/latest-tag/articles/teal-data.html)

Are these articles corresponding to the stable version?
![image](https://github.com/insightsengineering/teal/assets/68090582/7454edb7-cecd-4791-8071-943b11e56f65)

And I wonder if the following links on the bottom of the vignette, including the first one you mentioned, are all for development version? So it is probably a good idea for me to learn about them later right?
![image](https://github.com/insightsengineering/teal/assets/68090582/779e8b6b-6274-48ef-9c13-e85c4a3d287e)

Thanks in advance for reviewing me question!

**Comment by donyunardi** [comment]
> Are these articles corresponding to the stable version?

Correct. If you check on the top right for the version number, it should be something like x.y.z.
If you start seeing something like x.y.z.9### then you're in development environment.

> And I wonder if the following links on the bottom of the vignette, including the first one you mentioned, are all for development version? So it is probably a good idea for me to learn about them later right?

Hmmm... I thought it should point to other vignettes in `stable` version. We'll look into this. For your learning purposes, it would be better to stick with the `stable` version for now and review the dev version if you have time as you will probably need to learn this later =)

As helper, if you see `main` in your URL browser, just change it to `latest-tag`.

For example:
`https://insightsengineering.github.io/teal/main/articles/including-mae-data-in-teal.html`
to
`https://insightsengineering.github.io/teal/latest-tag/articles/including-mae-data-in-teal.html`

**Comment by Dannyzhd** [comment]
Got it. Thanks so much for the clarification, and thanks for the fantastic package!
