### ISSUE TITLE
Replace `TealData` with `teal_data` in the vignettes + Using `teal_data_module`

### ISSUE THREAD

**Issue by vedhav** [insightsengineering/teal#960]
Replace all instances of `TealData` in the vignettes with `teal_data` and write about how `teal_data` works especially about the `within()`

Vignettes affected:

- [x] Data in `teal` application. Let's create one vignette to replace former ones: https://github.com/insightsengineering/teal/pull/990
    - `preprocessing-data.Rmd` @chlebowa 
    -  `including-adam-data-in-teal.Rmd` @chlebowa 
    - `including-general-data-in-teal.Rmd` @chlebowa 
    - `including-mae-data-in-teal.Rmd` @chlebowa 
- [x] `creating-custom-modules.Rmd` use `teal_data` instead of `tdata` @chlebowa https://github.com/insightsengineering/teal/pull/980
- [x] `filter-panel.Rmd` (`data` and `filter` arguments) @chlebowa https://github.com/insightsengineering/teal/pull/981
- [x] `adding-support-for-reporting.Rmd` use `teal_data` instead of `tdata` @chlebowa https://github.com/insightsengineering/teal/pull/979
- [x] `teal-bs-themes.Rmd` @chlebowa https://github.com/insightsengineering/teal/pull/978

Extra: 
- [x] `teal.Rmd` has out-of-date picture of the filter panel @chlebowa https://github.com/insightsengineering/teal/pull/977

Assign yourself to single bulletpoint and make a PR for each file.

**Comment by chlebowa** [comment]
If the issue is "In Review", please link the corresponding pull requests.
