### ISSUE TITLE
plotly in Teal

### ISSUE THREAD

**Issue by dustreturn** [insightsengineering/teal#965]
### What is your question?

Is plotly available in teal package now? Or will it be available in the future?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
Hi @dustreturn 
We use some part on plotly in the visualization for range filtering in and currently that's the extend of it.

Can you elaborate on your question? Were you looking to use plotly in teal modules for output or visualization?

**Comment by donyunardi** [comment]
Closing due to lack of response.
