### ISSUE TITLE
`teal_data` appears empty when app starts

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal#985]
Warnings from `get_code_dependency` appear in console when the app starts and when a module is first viewed.

```
Warning in teal.data:::get_code_dependency(attr(datasets, "preprocessing_code"),  :
  Objects not found in 'qenv' environment: IRIS, NPK
```

Possibly related to data and module triggers.

https://github.com/insightsengineering/teal/assets/114988527/f080012a-a025-441f-b6c7-3d16c412a65d

#### example app on `@refactor` branch
```
devtools::load_all("../teal.transform")
devtools::load_all("../teal.data")
devtools::load_all("../teal.slice")
devtools::load_all("../teal")

app <- init(
  data = teal_data(IRIS = iris, NPK = npk),
  modules = modules(
    example_module(label = "example 1"),
    example_module(label = "example 2")
  )
)

runApp(app)
```

**Comment by kartikeyakirar** [comment]
it does for me as well
<img width="691" alt="image" src="https://github.com/insightsengineering/teal/assets/6700955/6ab96913-be0d-4d2e-b338-a4aa41618fd7">

**Comment by chlebowa** [comment]
For clarity, I have all packages installed from `main` and all repos checked out from `refactor`, which is why I use `load_all` for all of them.

**Comment by donyunardi** [comment]
I also can reproduce the warning:

![image](https://github.com/insightsengineering/teal/assets/8597300/26c775d0-3b22-4e13-bb97-c1bf8f858bf7)

The warning was from this line:
https://github.com/insightsengineering/teal/blob/5000351f8640b49858c29d110e04a2134258f561/R/get_rcode_utils.R#L49
